<?php

require_once dirname( __FILE__ ) . '/../../../../lib/core/ui/xlWidget.php';

/**
 * Test class for CXLWidget.
 * Generated by PHPUnit on 2011-03-05 at 22:24:24.
 */
class CXLWidgetTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var CXLWidget
	 */
	protected $object;

	/**
	 * @var array
	 */
	protected $_testOptions = array(
		'tagName' => 'span',
		'containerOptions' => array(
			'id' => 'my-widget-span',
		),
		'scriptFiles' => array(
			'/path/to/file/1.js',
			'/path/to/file/2.js',
			'/path/to/file/3.js',
			'/path/to/file/4.js',
		),
		'cssFiles' => array(
			'/path/to/file/1.css',
			'/path/to/file/2.css',
			'/path/to/file/3.css',
			'/path/to/file/4.css',
		)
	);

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new CXLWidget( $this, $this->_testOptions );
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @todo Implement testGetDebugLevel().
	 */
	public function testGetDebugLevel()
	{
		$this->object->setDebugLevel( E_ALL & ~E_NOTICE );
		$this->assertEquals( E_ALL & ~E_NOTICE, $this->object->getDebugLevel() );
	}

	/**
	 * @todo Implement testSetDebugLevel().
	 */
	public function testSetDebugLevel()
	{
		$this->object->setDebugLevel( false );
		$this->assertEquals( false, $this->object->getDebugLevel() );
	}

	/**
	 * @todo Implement testGetOptions().
	 */
	public function testGetOptions()
	{
		$this->assertEquals( $this->_testOptions, $this->object->getOptions() );
	}

	/**
	 * @todo Implement testGetOption().
	 */
	public function testGetOption()
	{
		$this->assertEquals( 'span', $this->object->getOption( 'tagName' ) );
	}

	/**
	 * @todo Implement testGetCssQueue().
	 */
	public function testGetCssQueue()
	{
	}

	/**
	 * @todo Implement testSetCssQueue().
	 */
	public function testSetCssQueue()
	{
	}

	/**
	 * @todo Implement testInit().
	 */
	public function testInit()
	{
	}

	/**
	 * @todo Implement testRun().
	 */
	public function testRun()
	{
	}

	/**
	 * @todo Implement testPushCssFile().
	 */
	public function testPushCssFile()
	{
	}

	/**
	 * @todo Implement testPopCssFile().
	 */
	public function testPopCssFile()
	{
	}

	/**
	 * @todo Implement testPushScriptFile().
	 */
	public function testPushScriptFile()
	{
	}

	/**
	 * @todo Implement testPopScriptFile().
	 */
	public function testPopScriptFile()
	{
	}

}

?>
