YiiXL -- The Yii Extension Library Of Doom!: CXLBaseJobProcess Class Reference
CXLBaseJobProcess Class Reference
Public Member Functions
getResultCode ()
setResultCode ($iValue)
getStatus ()
setStatus ($sValue)
getJobData ()
setJobData ($oValue)
getResult ()
__construct ($jobData=null, $autoRun=false)
Constructor.
run ()
Runs the job process with timing.
getProcessingTime ($rawOutput=false)
Returns the amount of time since the timer was started.
stopTimer ()
Stops the internal job timer.
startTimer ()
Starts the internal job timer.
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
getOption ($key, $defaultValue=null, $unsetAfter=false)
Gets a single configuration option.
attachBehavior ($name, $behavior)
Attaches a behavior to this component.
detachBehavior ($name)
Detaches a behavior from the component.
__call ($name, $parameters)
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.process.CXLBaseJobProcess'
Our logging tag.
Protected Member Functions
process ()
Process the job.
_runTimedProcess ()
Runs the process but stops the timer on the case of an exception.
Static Protected Member Functions
static _getCallerObject ($instanceFilter=null)
Walks the backtrace to find the calling object.
Protected Attributes
$_jobStartTime = null
$_jobEndTime = null
$_jobResultCode = null
$_jobStatus = null
$_jobData = null
$_jobResult = null
$_debugLevel = false
$_options
$_behaviorMethods
Detailed Description
Definition at line 37 of file CXLBaseJobProcess.php.
Constructor & Destructor Documentation
__construct ($ jobData = null, $ autoRun = false)
Constructor.
Parameters:
mixed $jobData Either a row from a job queue or data to process
boolean $autoRun If true, initializes and runs the job
Returns:
CXLBaseJobProcess
Definition at line 107 of file CXLBaseJobProcess.php.
References run().
Member Function Documentation
__call ($ name, $ parameters) [inherited]
Parameters:
string $name
array $parameters
Returns:
mixed
Definition at line 190 of file CXLComponent.php.
References YiiXLBase::smartCall().
static _getCallerObject ($ instanceFilter = null) [static, protected, inherited]
Walks the backtrace to find the calling object.
Parameters:
string $instanceFilter Only return objects of this instance
Definition at line 213 of file CXLComponent.php.
References YiiXLBase::o().
_runTimedProcess () [protected]
Runs the process but stops the timer on the case of an exception.
Returns:
mixed
Definition at line 175 of file CXLBaseJobProcess.php.
References process(), startTimer(), and stopTimer().
Referenced by run().
attachBehavior ($ name, $ behavior) [inherited]
Attaches a behavior to this component.
Calls the Yii implementation of this method, then injects the behaviors methods into our class.
Parameters:
string $name The behavior's name. It should uniquely identify this behavior.
mixed $behavior the behavior configuration. This is passed as the first parameter to YiiBase::createComponent to create the behavior object.
Returns:
IBehavior the behavior object
Definition at line 147 of file CXLComponent.php.
detachBehavior ($ name) [inherited]
Detaches a behavior from the component.
The behavior's IBehavior::detach method will be invoked.
Parameters:
string $name the behavior's name. It uniquely identifies the behavior.
Returns:
IBehavior the detached behavior. Null if the behavior does not exist.
Since:
1.0.2
Todo:
Implement un-importing methods
Definition at line 176 of file CXLComponent.php.
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 94 of file CXLComponent.php.
Referenced by YiiXLBase::smartCall().
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 67 of file CXLComponent.php.
getJobData ()
Definition at line 86 of file CXLBaseJobProcess.php.
getOption ($ key, $ defaultValue = null, $ unsetAfter = false) [inherited]
Gets a single configuration option.
Returns:
mixed
Definition at line 132 of file CXLComponent.php.
References YiiXLBase::o().
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 85 of file CXLComponent.php.
getProcessingTime ($ rawOutput = false)
Returns the amount of time since the timer was started.
Returns:
float
Definition at line 136 of file CXLBaseJobProcess.php.
References YiiXLBase::nvl().
getResult ()
Definition at line 94 of file CXLBaseJobProcess.php.
getResultCode ()
Definition at line 70 of file CXLBaseJobProcess.php.
getStatus ()
Definition at line 78 of file CXLBaseJobProcess.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 104 of file CXLComponent.php.
process () [abstract, protected]
Process the job.
Referenced by _runTimedProcess().
run ()
Runs the job process with timing.
Returns:
boolean
Definition at line 127 of file CXLBaseJobProcess.php.
References _runTimedProcess().
Referenced by __construct().
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Implements IXLComponent.
Definition at line 76 of file CXLComponent.php.
setJobData ($ oValue)
Definition at line 87 of file CXLBaseJobProcess.php.
setResultCode ($ iValue)
Definition at line 71 of file CXLBaseJobProcess.php.
setStatus ($ sValue)
Definition at line 79 of file CXLBaseJobProcess.php.
startTimer ()
Starts the internal job timer.
Definition at line 156 of file CXLBaseJobProcess.php.
Referenced by _runTimedProcess().
stopTimer ()
Stops the internal job timer.
Definition at line 147 of file CXLBaseJobProcess.php.
Referenced by _runTimedProcess().
Field Documentation
$_behaviorMethods [protected, inherited]
Definition at line 57 of file CXLComponent.php.
$_debugLevel = false [protected, inherited]
Definition at line 47 of file CXLComponent.php.
$_jobData = null [protected]
Definition at line 85 of file CXLBaseJobProcess.php.
$_jobEndTime = null [protected]
Definition at line 63 of file CXLBaseJobProcess.php.
$_jobResult = null [protected]
Definition at line 93 of file CXLBaseJobProcess.php.
$_jobResultCode = null [protected]
Definition at line 69 of file CXLBaseJobProcess.php.
$_jobStartTime = null [protected]
Definition at line 57 of file CXLBaseJobProcess.php.
$_jobStatus = null [protected]
Definition at line 77 of file CXLBaseJobProcess.php.
$_options [protected, inherited]
Reimplemented in CXLConfig.
Definition at line 52 of file CXLComponent.php.
const CLASS_LOG_TAG = 'yiixl.core.process.CXLBaseJobProcess'
Our logging tag.
Reimplemented from CXLComponent.
Definition at line 47 of file CXLBaseJobProcess.php.
The documentation for this class was generated from the following file:
CXLBaseJobProcess.php