YiiXL -- The Yii Extension Library Of Doom!: CXLActionControlBehavior Class Reference
CXLActionControlBehavior Class Reference
CXLActionControlBehavior Provides an alternative interface to configuring access to your actions.
Public Member Functions
getUserActionMap ($accessLevel)
Gets an UAM.
addUserActionRole ($accessLevel, $action, $role)
Adds a role to an access level/action.
removeUserAction ($accessLevel, $action)
Removes an access level/action pair.
addUserAction ($accessLevel, $action)
addUserActions ($accessLevel, $actions=array())
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.behaviors.CXLBehavior'
Our logging tag.
const ACCESS_TO_NONE = -1
const ACCESS_TO_ANY = 0
const ACCESS_TO_GUEST = 1
const ACCESS_TO_AUTH = 2
const ACCESS_TO_ADMIN = 3
const ACCESS_TO_ADMIN_LEVEL_0 = 3
const ACCESS_TO_ADMIN_LEVEL_1 = 4
const ACCESS_TO_ADMIN_LEVEL_2 = 5
Protected Member Functions
resetUserActionMap ()
Resets the UAM.
setUserActionMap ($accessLevel, $value=array())
Resets the UAM.
Protected Attributes
$_userActionMap = array()
An array of actions permitted by any user.
$_debugLevel = false
User-defined debug flag.
$_options
Our configuration options.
$_behaviorMethods
Imported attached behavior methods.
Detailed Description
CXLActionControlBehavior Provides an alternative interface to configuring access to your actions.
Definition at line 21 of file CXLActionControlControlBehavior.php.
Member Function Documentation
addUserAction ($ accessLevel, $ action)
Parameters:
type $accessLevel
type $action
Returns:
mixed
Definition at line 96 of file CXLActionControlControlBehavior.php.
References setUserActionMap().
Referenced by addUserActions(), and resetUserActionMap().
addUserActionRole ($ accessLevel, $ action, $ role)
Adds a role to an access level/action.
Parameters:
integer $accessLevel
string $action
string $role
Definition at line 74 of file CXLActionControlControlBehavior.php.
addUserActions ($ accessLevel, $ actions = array())
Parameters:
integer $accessLevel
array $actions
Definition at line 117 of file CXLActionControlControlBehavior.php.
References addUserAction().
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 92 of file CXLBehavior.php.
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 63 of file CXLBehavior.php.
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 83 of file CXLBehavior.php.
getUserActionMap ($ accessLevel)
Gets an UAM.
Parameters:
\$accessLevel Retrieves the UAM for this access level.
Returns:
array
Definition at line 41 of file CXLActionControlControlBehavior.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
$this
Implements IXLComponent.
Definition at line 102 of file CXLBehavior.php.
removeUserAction ($ accessLevel, $ action)
Removes an access level/action pair.
Parameters:
integer $accessLevel
string $action
Returns:
mixed Returns the previous value or null
Definition at line 86 of file CXLActionControlControlBehavior.php.
resetUserActionMap () [protected]
Resets the UAM.
Definition at line 49 of file CXLActionControlControlBehavior.php.
References addUserAction().
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Returns:
$this
Implements IXLComponent.
Definition at line 73 of file CXLBehavior.php.
setUserActionMap ($ accessLevel, $ value = array()) [protected]
Resets the UAM.
Parameters:
integer $accessLevel
array $value
Returns:
CXLActionControlBehavior
Definition at line 62 of file CXLActionControlControlBehavior.php.
Referenced by addUserAction().
Field Documentation
array $_behaviorMethods [protected, inherited]
Imported attached behavior methods.
Definition at line 53 of file CXLBehavior.php.
integer $_debugLevel = false [protected, inherited]
User-defined debug flag.
false = OFF, anything else is up to you.
Definition at line 41 of file CXLBehavior.php.
array $_options [protected, inherited]
Our configuration options.
Definition at line 47 of file CXLBehavior.php.
$_userActionMap = array() [protected]
An array of actions permitted by any user.
Definition at line 30 of file CXLActionControlControlBehavior.php.
const CLASS_LOG_TAG = 'yiixl.core.behaviors.CXLBehavior' [inherited]
Our logging tag.
Reimplemented in CXLOAuthBehavior.
Definition at line 31 of file CXLBehavior.php.
The documentation for this class was generated from the following file:
CXLActionControlControlBehavior.php