YiiXL -- The Yii Extension Library Of Doom!: YiiXLBase Class Reference
YiiXLBase Class Reference
YiiXLBase.
Public Member Functions
_gf ($key, $defaultValue=null, $delete=true)
Returns a flash message.
Static Public Member Functions
static getParams ()
Returns the cached copy of the configured application parameters {.
static getClassPath ()
static setClassPath ($classPath)
static addClassToPath ($className)
static initialize ($options=array())
Initialize our private statics.
static createUniqueName (IXLComponent $component, $humanReadable=false)
Constructs a unique name based on component, hashes by default.
static nvl ()
NVL = Null VaLue.
static in ()
Convenience "in_array" method.
static microtime ()
Returns the current microtime in more readable format.
static getOption (&$options=array(), $key, $defaultValue=null, $unsetValue=false)
Alias for CXLHelperBase::o).
static o (&$options=array(), $key, $defaultValue=null, $unsetValue=false)
Retrieves an option from the given array.
static oo (&$options=array(), $key, $subKey, $defaultValue=null, $unsetValue=false)
Similar to XL::o except it will pull a value from a nested array.
static setOption (array &$options, $key, $value=null)
Alias for CXLHelperBase::so.
static so (array &$options, $key, $value=null)
Sets an option in the given array.
static unsetOption (array &$options, $key)
Alias of CXLHelperBase::unsetOption.
static uo (array &$options, $key)
Unsets an option in the given array.
static makeArray ()
Takes parameters and returns an array of the values.
static makePath ()
Takes the arguments and makes a file path out of them.
static _a ()
Shorthand version of Yii::app().
static getAppName ($notEncoded=false)
Convenience method returns the current app name.
static _gan ($notEncoded=false)
static getPageTitle ($notEncoded=false)
Convienice method returns the current page title.
static _gpt ($notEncoded=false)
static getBaseUrl ($absolute=false)
Convienice methond Returns the base url of the current app.
static _gbu ($absolute=false)
static getBasePath ()
Convienice methond Returns the base path of the current app.
static _gbp ()
static getClientScript ()
static _cs ()
Returns the current clientScript object.
static _end ($status=0, $exit=true)
Terminates the application.
static getDb ()
static _db ()
static registerScriptFile ($url, $ePosition=self::POS_HEAD, $fromPublished=false)
Registers a javascript file.
static _rsf ($urlList, $pagePosition=CClientScript::POS_HEAD, $fromPublished=false)
Registers a javascript file.
static registerCssFile ($url, $media= '', $fromPublished=false)
Registers a CSS file.
static _rcf ($urlList, $media= '', $fromPublished=false)
Registers a CSS file.
static _rlcf ($urlList, $media= '', $fromPublished=false)
Registers a CSS file relative to the current layout directory.
static registerCss ($css, $options=array())
Registers a piece of CSS code.
static _rc ($sId=null, $sCss, $media= '')
Registers a piece of CSS code.
static registerScript ($sId=null, $sScript, $ePosition=CClientScript::POS_READY)
Registers a piece of javascript code.
static _rs ($sId=null, $sScript, $ePosition=CClientScript::POS_READY)
Registers a piece of javascript code.
static registerMetaTag ($sContent, $sName=null, $sHttpEquiv=null, $options=array())
Registers a meta tag that will be inserted in the head section (right before the title element) of the resulting page.
static _rmt ($sContent, $sName=null, $sHttpEquiv=null, $options=array())
Registers a meta tag that will be inserted in the head section (right before the title element) of the resulting page.
static _cu ($route, $options=array(), $ampersand= '&')
Creates a relative URL based on the given controller and action information.
static getRequest ()
Returns the current request.
static _gr ()
Returns the current request.
static getUser ()
Returns the current user.
static _gu ()
static getCurrentUser ()
Returns the currently logged in user.
static _gcu ()
static isGuest ()
Returns boolean indicating if user is logged in or not.
static _ig ()
static getParam ($paramName, $defaultValue=null)
Returns application parameters or default value if not found.
static _gp ($paramName, $defaultValue=null)
static getController ()
static _gc ()
static getComponent ($id, $createIfNull=true)
static _gco ($id, $createIfNull=true)
static _publish ($path, $hashByName=false, $level=-1)
Convenience access to CAssetManager::publish().
static redirect ($url, $terminate=true, $statusCode=302)
Performs a redirect.
static _gs ($stateName, $defaultValue=null)
Returns the value of a variable that is stored in the user session.
static _ghs ($stateKeyParts, $defaultValue=null)
Alternative to CWebUser::getState that takes an array of key parts and assembles them into a hashed key.
static _ss ($stateName, $stateValue, $defaultValue=null)
Stores a variable from the user session.
static _shs ($stateKeyParts, $stateValue, $defaultValue=null)
Alternative to CWebUser::setState that takes an array of key parts and assembles them into a hashed key.
static _sf ($key, $value, $defaultValue=null)
Stores a flash message.
static _ge ()
Returns the details about the error that is currently being handled.
static _sql ($sql, $dbToUse=null)
Creates and returns a CDbCommand object from the specified SQL.
static _sqlAll ($sql, $parameterList=array(), $dbToUse=null)
Executes the given sql statement and returns all results.
static _sqlAllScalar ($sql, $parameterList=null, $dbToUse=null)
Executes the given sql statement and returns the first column of all results in an array.
static isCLI ()
Determine if PHP is running CLI mode or not.
static _spoa ($alias, $path)
Create a path alias.
static _gpoa ($alias, $url=null)
Translates an alias into a file path.
static isPostRequest ()
static isAjaxRequest ()
static filterInt ($value, $nullIfZero=true, $min=null, $max=null)
Filters an int optionally returns null.
static smartCall (CXLComponent $object, $method, $parameters=array())
This is a standardized magic method "helper".
static smartCallStatic (IXLComponent $object, $method, $parameters=array())
Calls a static method in classPath if not found here.
static __callStatic ($method, $parameters)
Calls a static method in classPath if not found here.
static initialize ()
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.YiiXLBase'
Our logging tag.
const OF_JSON = 0
Standard output formats.
const OF_HTTP = 1
const OF_ASSOC_ARRAY = 2
const OF_XML = 3
const PL_TOP_LEFT = 0
Pager locations.
const PL_TOP_RIGHT = 1
const PL_BOTTOM_LEFT = 2
const PL_BOTTOM_RIGHT = 3
const ACTION_NONE = 0
const ACTION_CREATE = 1
const ACTION_VIEW = 2
const ACTION_EDIT = 3
const ACTION_SAVE = 4
const ACTION_DELETE = 5
const ACTION_ADMIN = 6
const ACTION_LOCK = 7
const ACTION_UNLOCK = 8
const ACTION_PREVIEW = 996
const ACTION_RETURN = 997
const ACTION_CANCEL = 998
const ACTION_GENERIC = 999
const LOG_EMERG = 0
Logging Constants.
const LOG_ALERT = 1
const LOG_CRIT = 2
const LOG_ERR = 3
const LOG_WARNING = 4
const LOG_NOTICE = 5
const LOG_INFO = 6
const LOG_DEBUG = 7
const LOG_USER = 8
const LOG_AUTH = 32
const LOG_SYSLOG = 40
const LOG_AUTHPRIV = 80
Static Protected Member Functions
static _serialize ($value)
Serializer that can handle SimpleXmlElement objects.
static _unserialize ($value)
Unserializer that can handle SimpleXmlElement objects.
static _isSerialized ($value)
Tests if a value needs unserialization.
Static Protected Attributes
static $_thisApp = null
Cache the current app for speed CWebApplication $thisApp.
static $_thisRequest = null
Cache the current request CHttpRequest $thisRequest.
static $_clientScript = null
Cache the client script object for speed CClientScript $clientScript.
static $_thisUser = null
Cache the user object for speed CWebUser $thisUser.
static $_thisController = null
Cache the current controller for speed CController $thisController.
static $_validLogLevels
array $_validLogLevels Our valid log levels based on interface definition
static $_uniqueIdCounter = 1000
A static ID counter for generating unique names integer $_uniqueIdCounter.
static $_appParameters = null
Cache the application parameters for speed CAttributeCollection $appParameters.
static $_classPath
An array of class names to search in for missing static methods.
Detailed Description
YiiXLBase.
The Mother Of All YiiXL Classes!
Definition at line 32 of file YiiXLBase.php.
Member Function Documentation
static __callStatic ($ method, $ parameters) [static]
Calls a static method in classPath if not found here.
Allows you to extend this object at runtime with additional helpers.
Only available in PHP 5.3+
Parameters:
string $method
array $parameters
Returns:
mixed
Definition at line 1236 of file YiiXLBase.php.
static _a () [static]
Shorthand version of Yii::app().
Returns:
CApplication the application singleton, null if the singleton has not been created yet.
Definition at line 410 of file YiiXLBase.php.
Referenced by _gan(), _ge(), CXLWebModule::_setAssetPaths(), and CXLController::init().
static _cs () [static]
Returns the current clientScript object.
Caches for subsequent calls...
Returns:
CClientScript public
Definition at line 497 of file YiiXLBase.php.
static _cu ($ route, $ options = array(), $ ampersand = '&') [static]
Creates a relative URL based on the given controller and action information.
Parameters:
string the URL route. This should be in the format of 'ControllerID/ActionID'.
array additional GET parameters (name=>value). Both the name and value will be URL-encoded.
string the token separating name-value pairs in the URL.
Returns:
string the constructed URL
Definition at line 742 of file YiiXLBase.php.
static _db () [static]
Definition at line 523 of file YiiXLBase.php.
Referenced by getDb().
static _end ($ status = 0, $ exit = true) [static]
Terminates the application.
This method replaces PHP's exit() function by calling onEndRequest before exiting.
Parameters:
integer $status exit status (value 0 means normal exit while other values mean abnormal exit).
boolean $exit whether to exit the current request. This parameter has been available since version 1.1.5. It defaults to true, meaning the PHP's exit() function will be called at the end of this method. public
Definition at line 510 of file YiiXLBase.php.
static _gan ($ notEncoded = false) [static]
Definition at line 426 of file YiiXLBase.php.
References _a().
Referenced by getAppName(), CXLController::setStandardFormOptions(), and CXLController::setViewNavigationOptions().
static _gbp () [static]
Definition at line 474 of file YiiXLBase.php.
Referenced by CXLController::init().
static _gbu ($ absolute = false) [static]
Definition at line 458 of file YiiXLBase.php.
Referenced by CXLWidget::_renderCss(), CXLWidget::_renderScripts(), and CXLController::getAppBaseUrl().
static _gc () [static]
Definition at line 837 of file YiiXLBase.php.
References getController().
Referenced by _gpt(), and getController().
static _gco ($ id, $ createIfNull = true) [static]
Definition at line 851 of file YiiXLBase.php.
Referenced by CXLController::actionError(), and getComponent().
static _gcu () [static]
Definition at line 791 of file YiiXLBase.php.
References _gs().
Referenced by getCurrentUser(), and CXLController::init().
static _ge () [static]
Returns the details about the error that is currently being handled.
The error is returned in terms of an array, with the following information:
code - the HTTP status code (e.g. 403, 500)
type - the error type (e.g. 'CHttpException', 'PHP Error')
message - the error message
file - the name of the PHP script file where the error occurs
line - the line number of the code where the error occurs
trace - the call stack of the error
source - the context source code where the error occurs
Returns:
array the error details. Null if there is no error.
Definition at line 1013 of file YiiXLBase.php.
References _a().
_gf ($ key, $ defaultValue = null, $ delete = true)
Returns a flash message.
A flash message is available only in the current and the next requests.
Parameters:
string $key key identifying the flash message
mixed $defaultValue value to be returned if the flash message is not available.
boolean $delete whether to delete this flash message after accessing it. Defaults to true. This parameter has been available since version 1.0.2.
Returns:
mixed the message message
See also:
_sf
Definition at line 944 of file YiiXLBase.php.
References _gu().
Referenced by CXLController::setStandardFormOptions().
static _ghs ($ stateKeyParts, $ defaultValue = null) [static]
Alternative to CWebUser::getState that takes an array of key parts and assembles them into a hashed key.
Parameters:
array Array of key parts
mixed default value
Returns:
mixed the value of the variable. If it doesn't exist in the session, the provided default value will be returned
See also:
_ss
_gs
CWebUser::setState
Definition at line 929 of file YiiXLBase.php.
References _gs().
static _gp ($ paramName, $ defaultValue = null) [static]
Definition at line 821 of file YiiXLBase.php.
Referenced by getParam().
static _gpoa ($ alias, $ url = null) [static]
Translates an alias into a file path.
Note, this method does not ensure the existence of the resulting file path. It only checks if the root alias is valid or not.
Parameters:
string $alias alias (e.g. system.web.CController)
string $url Additional url combine with alias
Returns:
mixed file path corresponding to the alias, false if the alias is invalid.
Definition at line 1098 of file YiiXLBase.php.
static _gpt ($ notEncoded = false) [static]
Definition at line 442 of file YiiXLBase.php.
References _gc(), and getPageTitle().
Referenced by getPageTitle().
static _gr () [static]
Returns the current request.
Equivalent of CApplication::getRequest
See also:
CApplication::getRequest
Returns:
CHttpRequest
Definition at line 762 of file YiiXLBase.php.
Referenced by getRequest(), CXLController::getRequest(), isAjaxRequest(), and isPostRequest().
static _gs ($ stateName, $ defaultValue = null) [static]
Returns the value of a variable that is stored in the user session.
This function is designed to be used by CWebUser descendant classes to store additional user information the user's session. A variable, if stored in the session using _ss can be retrieved back using this function.
Parameters:
string variable name
mixed default value
Returns:
mixed the value of the variable. If it doesn't exist in the session, the provided default value will be returned
See also:
_ss
CWebUser::setState
Definition at line 914 of file YiiXLBase.php.
References _gu().
Referenced by _gcu(), _ghs(), and CXLOAuthBehavior::loadToken().
static _gu () [static]
Definition at line 777 of file YiiXLBase.php.
Referenced by _gf(), _gs(), _ig(), _ss(), and getUser().
static _ig () [static]
Definition at line 805 of file YiiXLBase.php.
References _gu().
Referenced by isGuest().
static _isSerialized ($ value) [static, protected]
Tests if a value needs unserialization.
Parameters:
mixed $value
Returns:
boolean
Definition at line 1298 of file YiiXLBase.php.
static _publish ($ path, $ hashByName = false, $ level = -1) [static]
Convenience access to CAssetManager::publish().
Publishes a file or a directory. This method will copy the specified asset to a web accessible directory and return the URL for accessing the published asset.
If the asset is a file, its file modification time will be checked to avoid unnecessary file copying;
If the asset is a directory, all files and subdirectories under it will be published recursively. Note, in this case the method only checks the existence of the target directory to avoid repetitive copying.
Parameters:
string the asset (file or directory) to be published
boolean whether the published directory should be named as the hashed basename. If false, the name will be the hashed dirname of the path being published. Defaults to false. Set true if the path being published is shared among different extensions.
integer level of recursive copying when the asset is a directory. Level -1 means publishing all subdirectories and files; Level 0 means publishing only the files DIRECTLY under the directory; level N means copying those directories that are within N levels.
Returns:
string an absolute URL to the published asset
Exceptions:
CException if the asset to be published does not exist.
See also:
CAssetManager::publish
Definition at line 882 of file YiiXLBase.php.
static _rc ($ sId = null, $ sCss, $ media = '') [static]
Registers a piece of CSS code.
Parameters:
string ID that uniquely identifies this piece of CSS code
string the CSS code
string media that the CSS code should be applied to. If empty, it means all media types. public
Definition at line 658 of file YiiXLBase.php.
References nvl().
Referenced by registerCss().
static _rcf ($ urlList, $ media = '', $ fromPublished = false) [static]
Registers a CSS file.
Parameters:
string URL of the CSS file
string media that the CSS file should be applied to. If empty, it means all media types. public
Definition at line 596 of file YiiXLBase.php.
References registerCssFile().
Referenced by CXLWidget::_renderCss(), and registerCssFile().
static _rlcf ($ urlList, $ media = '', $ fromPublished = false) [static]
Registers a CSS file relative to the current layout directory.
Parameters:
string relative URL of the CSS file
string media that the CSS file should be applied to. If empty, it means all media types. public
Definition at line 617 of file YiiXLBase.php.
References registerCssFile().
static _rmt ($ sContent, $ sName = null, $ sHttpEquiv = null, $ options = array()) [static]
Registers a meta tag that will be inserted in the head section (right before the title element) of the resulting page.
Parameters:
string content attribute of the meta tag
string name attribute of the meta tag. If null, the attribute will not be generated
string http-equiv attribute of the meta tag. If null, the attribute will not be generated
array other options in name-value pairs (e.g. 'scheme', 'lang') public
Definition at line 730 of file YiiXLBase.php.
Referenced by registerMetaTag().
static _rs ($ sId = null, $ sScript, $ ePosition = CClientScript::POS_READY) [static]
Registers a piece of javascript code.
Parameters:
string ID that uniquely identifies this piece of JavaScript code
string the javascript code
integer the position of the JavaScript code. Valid values include the following:
CClientScript::POS_HEAD : the script is inserted in the head section right before the title element.
CClientScript::POS_BEGIN : the script is inserted at the beginning of the body section.
CClientScript::POS_END : the script is inserted at the end of the body section.
CClientScript::POS_LOAD : the script is inserted in the window.onload() function.
CClientScript::POS_READY : the script is inserted in the jQuery's ready function.
public
Definition at line 700 of file YiiXLBase.php.
References nvl().
Referenced by registerScript(), and CXLController::setStandardFormOptions().
static _rsf ($ urlList, $ pagePosition = CClientScript::POS_HEAD, $ fromPublished = false) [static]
Registers a javascript file.
Parameters:
array|string $urlList Urls of scripts to load. If URL starts with '!', asset library will be prepended. If first character is not a '/', the asset library directory is prepended.
integer $pagePosition the position of the JavaScript code. Valid values include the following:
CClientScript::POS_HEAD : the script is inserted in the head section right before the title element.
CClientScript::POS_BEGIN : the script is inserted at the beginning of the body section.
CClientScript::POS_END : the script is inserted at the end of the body section.
boolean $fromPublished If true, asset library directory is prepended to url public
Definition at line 560 of file YiiXLBase.php.
References registerScriptFile().
Referenced by CXLWidget::_renderScripts(), and registerScriptFile().
static _serialize ($ value) [static, protected]
Serializer that can handle SimpleXmlElement objects.
Parameters:
mixed $value
Returns:
mixed
Definition at line 1253 of file YiiXLBase.php.
static _sf ($ key, $ value, $ defaultValue = null) [static]
Stores a flash message.
A flash message is available only in the current and the next requests.
Parameters:
string $key key identifying the flash message
mixed $value flash message
mixed $defaultValue if this value is the same as the flash message, the flash message will be removed. (Therefore, you can use setFlash('key',null) to remove a flash message.)
See also:
CXLHelperBase#_gf
Definition at line 994 of file YiiXLBase.php.
Referenced by CXLController::genericAction().
static _shs ($ stateKeyParts, $ stateValue, $ defaultValue = null) [static]
Alternative to CWebUser::setState that takes an array of key parts and assembles them into a hashed key.
Parameters:
array array of key parts
mixed variable value
mixed default value
See also:
_ss
_gs
CWebUser::setState
Definition at line 980 of file YiiXLBase.php.
References _ss().
static _spoa ($ alias, $ path) [static]
Create a path alias.
Note, this method neither checks the existence of the path nor normalizes the path.
Parameters:
string $alias alias to the path
string $path the path corresponding to the alias. If this is null, the corresponding path alias will be removed.
Definition at line 1085 of file YiiXLBase.php.
static _sql ($ sql, $ dbToUse = null) [static]
Creates and returns a CDbCommand object from the specified SQL.
Parameters:
string $sql
Returns:
CDbCommand
Definition at line 1024 of file YiiXLBase.php.
References getDb(), and nvl().
static _sqlAll ($ sql, $ parameterList = array(), $ dbToUse = null) [static]
Executes the given sql statement and returns all results.
Parameters:
string $sql
array $parameterList List of parameters for call
CDbConnection $dbToUse
Returns:
mixed
Definition at line 1038 of file YiiXLBase.php.
References getDb(), and nvl().
static _sqlAllScalar ($ sql, $ parameterList = null, $ dbToUse = null) [static]
Executes the given sql statement and returns the first column of all results in an array.
Parameters:
string $sql
array $parameterList List of parameters for call
CDbConnection $dbToUse
Returns:
array
Definition at line 1052 of file YiiXLBase.php.
References getDb(), and nvl().
static _ss ($ stateName, $ stateValue, $ defaultValue = null) [static]
Stores a variable from the user session.
This function is designed to be used by CWebUser descendant classes who want to store additional user information in user session. By storing a variable using this function, the variable may be retrieved back later using _gs. The variable will be persistent across page requests during a user session.
Parameters:
string variable name
mixed variable value
mixed default value. If $value === $defaultValue (i.e. null), the variable will be removed from the session
See also:
_gs
CWebUser::getState
Definition at line 965 of file YiiXLBase.php.
References _gu().
Referenced by _shs(), CXLController::setStandardFormOptions(), and CXLOAuthBehavior::storeToken().
static _unserialize ($ value) [static, protected]
Unserializer that can handle SimpleXmlElement objects.
Parameters:
mixed $value
Returns:
mixed
Definition at line 1274 of file YiiXLBase.php.
static addClassToPath ($ className) [static]
Definition at line 117 of file YiiXLBase.php.
Referenced by initialize().
static createUniqueName (IXLComponent $ component, $ humanReadable = false) [static]
Constructs a unique name based on component, hashes by default.
Parameters:
IXLComponent $component
boolean $humanReadable If true, names returned will not be hashed
Returns:
string
Definition at line 182 of file YiiXLBase.php.
References CXLHash::hash().
Referenced by registerCss().
static filterInt ($ value, $ nullIfZero = true, $ min = null, $ max = null) [static]
Filters an int optionally returns null.
Parameters:
mixed $value
boolean $nullIfZero
integer $min
integer $max
Returns:
integer Filtered value or false on error
Definition at line 1135 of file YiiXLBase.php.
static getAppName ($ notEncoded = false) [static]
Convenience method returns the current app name.
See also:
CWebApplication::name
CHtml::encode
Returns:
string
Definition at line 421 of file YiiXLBase.php.
References _gan().
static getBasePath () [static]
Convienice methond Returns the base path of the current app.
See also:
CWebApplication::getBasePath
CHttpRequest::getBasePath
Returns:
string
Definition at line 469 of file YiiXLBase.php.
static getBaseUrl ($ absolute = false) [static]
Convienice methond Returns the base url of the current app.
See also:
CWebApplication::getBaseUrl
CHttpRequest::getBaseUrl
Returns:
string
Definition at line 453 of file YiiXLBase.php.
static getClassPath () [static]
Definition at line 107 of file YiiXLBase.php.
static getClientScript () [static]
Definition at line 486 of file YiiXLBase.php.
static getComponent ($ id, $ createIfNull = true) [static]
Returns:
CComponent The component, if found
See also:
CWebApplication::getComponent
Definition at line 846 of file YiiXLBase.php.
References _gco().
static getController () [static]
Returns:
CController the currently active controller
See also:
CWebApplication::getController
Definition at line 832 of file YiiXLBase.php.
References _gc().
Referenced by _gc().
static getCurrentUser () [static]
Returns the currently logged in user.
Returns:
CWebUser
Definition at line 786 of file YiiXLBase.php.
References _gcu().
static getDb () [static]
Returns:
CDbConnection the database connection
Definition at line 518 of file YiiXLBase.php.
References _db().
Referenced by _sql(), _sqlAll(), and _sqlAllScalar().
static getOption (&$ options = array(), $ key, $ defaultValue = null, $ unsetValue = false) [static]
Alias for CXLHelperBase::o).
Parameters:
array $options
string $key
mixed $defaultValue
boolean $unsetValue
Returns:
mixed public
Definition at line 253 of file YiiXLBase.php.
References o().
static getPageTitle ($ notEncoded = false) [static]
Convienice method returns the current page title.
See also:
CController::pageTitle
CHtml::encode
Returns:
string
Definition at line 437 of file YiiXLBase.php.
References _gpt().
Referenced by _gpt().
static getParam ($ paramName, $ defaultValue = null) [static]
Returns application parameters or default value if not found.
See also:
CModule::getParams
CModule::setParams
Returns:
mixed
Definition at line 816 of file YiiXLBase.php.
References _gp().
static getParams () [static]
Returns the cached copy of the configured application parameters {.
See also:
CWebApplication::getParams}
Returns:
array
Definition at line 91 of file YiiXLBase.php.
static getRequest () [static]
Returns the current request.
Equivalent of CApplication::getRequest
See also:
CApplication::getRequest
Returns:
CHttpRequest
Definition at line 752 of file YiiXLBase.php.
References _gr().
static getUser () [static]
Returns the current user.
Equivalent of CWebApplication::getUser
See also:
CWebApplication::getUser
Returns:
CUserIdentity
Definition at line 772 of file YiiXLBase.php.
References _gu().
static in () [static]
Convenience "in_array" method.
Takes variable args.
The first argument is the needle, the rest are considered in the haystack. For example:
CXLHelperBase::in('x', 'x', 'y', 'z') returns true CXLHelperBase::in('a', 'x', 'y', 'z') returns false
Parameters:
mixed
Returns:
boolean
Definition at line 223 of file YiiXLBase.php.
static initialize () [static, inherited]
Implemented in CXLBaseHelper.
static initialize ($ options = array()) [static]
Initialize our private statics.
Definition at line 129 of file YiiXLBase.php.
References addClassToPath().
static isAjaxRequest () [static]
Returns:
boolean True if this is an AJAX (xhr) request.
Definition at line 1118 of file YiiXLBase.php.
References _gr().
Referenced by CXLController::getIsAjaxRequest().
static isCLI () [static]
Determine if PHP is running CLI mode or not.
Returns:
boolean True if currently running in CLI
Definition at line 1073 of file YiiXLBase.php.
static isGuest () [static]
Returns boolean indicating if user is logged in or not.
Returns:
boolean
Definition at line 800 of file YiiXLBase.php.
References _ig().
static isPostRequest () [static]
Returns:
boolean whether this is POST request.
Definition at line 1110 of file YiiXLBase.php.
References _gr().
Referenced by CXLController::getIsPostRequest().
static makeArray () [static]
Takes parameters and returns an array of the values.
Keys are maintained.
Parameters:
mixed Zero or more values to read and put into the return array.
Returns:
array
Definition at line 380 of file YiiXLBase.php.
Referenced by CXLTimeStampBehavior::touch().
static makePath () [static]
Takes the arguments and makes a file path out of them.
No leading or trailing separator is added.
Parameters:
mixed File path parts
Returns:
string
Definition at line 397 of file YiiXLBase.php.
static microtime () [static]
Returns the current microtime in more readable format.
Returns:
integer
Definition at line 236 of file YiiXLBase.php.
static nvl () [static]
NVL = Null VaLue.
Copycat function from PL/SQL. Pass in a list of arguments and the first non-null item is returned. Good for setting default values, etc. Last non-null value in list becomes the new "default value".
NOTE: Since PHP evaluates the arguments before calling a function, this is NOT a short-circuit method.
Parameters:
mixed
Returns:
mixed
Definition at line 198 of file YiiXLBase.php.
Referenced by CXLController::_loadPaged(), _rc(), _rs(), CXLController::_saveCurrentModel(), _sql(), _sqlAll(), _sqlAllScalar(), CXLDataTransformBehavior::getFormat(), and CXLBaseJobProcess::getProcessingTime().
static o (&$ options = array(), $ key, $ defaultValue = null, $ unsetValue = false) [static]
Retrieves an option from the given array.
$defaultValue is set and returned if $key is not 'set'. Optionally will unset option in array.
Parameters:
array $options
integer|string $key
integer|string $subKey
mixed $defaultValue
boolean $unsetValue
Returns:
mixed public
See also:
CXLHelperBase::getOption
Definition at line 272 of file YiiXLBase.php.
Referenced by CXLComponent::_getCallerObject(), CXLController::_loadPaged(), CXLController::_processCommand(), CXLSoftDeleteBehavior::beforeDelete(), CXLSoftDeleteBehavior::beforeFind(), getOption(), CXLWidget::getOption(), CXLConfig::getOption(), CXLComponent::getOption(), CXLWidget::init(), CXLController::init(), CXLController::loadCurrentModel(), oo(), registerCss(), CXLController::setStandardFormOptions(), CXLController::setViewNavigationOptions(), smartCall(), CXLSoftDeleteBehavior::undelete(), and uo().
static oo (&$ options = array(), $ key, $ subKey, $ defaultValue = null, $ unsetValue = false) [static]
Similar to XL::o except it will pull a value from a nested array.
Parameters:
array $options
integer|string $key
integer|string $subKey
mixed $defaultValue Only applies to target value
boolean $unsetValue Only applies to target value
Returns:
mixed
Definition at line 318 of file YiiXLBase.php.
References o().
static redirect ($ url, $ terminate = true, $ statusCode = 302) [static]
Performs a redirect.
See CHttpRequest::redirect
Parameters:
string $url
boolean $terminate
int $statusCode
See also:
CHttpRequest::redirect
Definition at line 895 of file YiiXLBase.php.
static registerCss ($ css, $ options = array()) [static]
Registers a piece of CSS code.
Parameters:
string ID that uniquely identifies this piece of CSS code
string the CSS code
string media that the CSS code should be applied to. If empty, it means all media types. public
Definition at line 639 of file YiiXLBase.php.
References _rc(), createUniqueName(), and o().
static registerCssFile ($ url, $ media = '', $ fromPublished = false) [static]
Registers a CSS file.
Parameters:
string URL of the CSS file
string media that the CSS file should be applied to. If empty, it means all media types.
boolean If true, asset library directory is prepended to url public
Definition at line 583 of file YiiXLBase.php.
References _rcf().
Referenced by _rcf(), and _rlcf().
static registerMetaTag ($ sContent, $ sName = null, $ sHttpEquiv = null, $ options = array()) [static]
Registers a meta tag that will be inserted in the head section (right before the title element) of the resulting page.
Parameters:
string content attribute of the meta tag
string name attribute of the meta tag. If null, the attribute will not be generated
string http-equiv attribute of the meta tag. If null, the attribute will not be generated
array other options in name-value pairs (e.g. 'scheme', 'lang') public
Definition at line 715 of file YiiXLBase.php.
References _rmt().
static registerScript ($ sId = null, $ sScript, $ ePosition = CClientScript::POS_READY) [static]
Registers a piece of javascript code.
Parameters:
string ID that uniquely identifies this piece of JavaScript code
string the javascript code
integer the position of the JavaScript code. Valid values include the following:
CClientScript::POS_HEAD : the script is inserted in the head section right before the title element.
CClientScript::POS_BEGIN : the script is inserted at the beginning of the body section.
CClientScript::POS_END : the script is inserted at the end of the body section.
CClientScript::POS_LOAD : the script is inserted in the window.onload() function.
CClientScript::POS_READY : the script is inserted in the jQuery's ready function.
public
Definition at line 679 of file YiiXLBase.php.
References _rs().
static registerScriptFile ($ url, $ ePosition = self::POS_HEAD, $ fromPublished = false) [static]
Registers a javascript file.
Parameters:
string URL of the javascript file
integer the position of the JavaScript code. Valid values include the following:
CClientScript::POS_HEAD : the script is inserted in the head section right before the title element.
CClientScript::POS_BEGIN : the script is inserted at the beginning of the body section.
CClientScript::POS_END : the script is inserted at the end of the body section.
public
Definition at line 541 of file YiiXLBase.php.
References _rsf().
Referenced by _rsf().
static setClassPath ($ classPath) [static]
Definition at line 112 of file YiiXLBase.php.
static setOption (array &$ options, $ key, $ value = null) [static]
Alias for CXLHelperBase::so.
Parameters:
array $options
string $key
mixed $value
Returns:
mixed The new value of the key
Definition at line 332 of file YiiXLBase.php.
References so().
static smartCall (CXLComponent $ object, $ method, $ parameters = array()) [static]
This is a standardized magic method "helper".
Parameters:
CXLComponent $object
array $behaviors
string $method
array $parameters
Returns:
mixed
Definition at line 1163 of file YiiXLBase.php.
References CXLComponent::getBehaviorMethods(), o(), and smartCallStatic().
Referenced by CXLComponent::__call().
static smartCallStatic (IXLComponent $ object, $ method, $ parameters = array()) [static]
Calls a static method in classPath if not found here.
Allows you to extend this object at runtime with additional helpers. Injects $object into parameter list.
Parameters:
IXLComponent $object
string $method
array $parameters
Returns:
mixed
Exceptions:
CXLMethodNotFoundException
Definition at line 1198 of file YiiXLBase.php.
Referenced by smartCall().
static so (array &$ options, $ key, $ value = null) [static]
Sets an option in the given array.
Parameters:
array $options
string $key
mixed $value Defaults to null
Returns:
mixed The new value of the key
Definition at line 345 of file YiiXLBase.php.
Referenced by setOption().
static unsetOption (array &$ options, $ key) [static]
Alias of CXLHelperBase::unsetOption.
Parameters:
array $options
string $key
Returns:
mixed The last value of the key
Definition at line 357 of file YiiXLBase.php.
References uo().
static uo (array &$ options, $ key) [static]
Unsets an option in the given array.
Parameters:
array $options
string $key
Returns:
mixed The last value of the key
Definition at line 370 of file YiiXLBase.php.
References o().
Referenced by CXLConfig::__unset(), and unsetOption().
Field Documentation
$_appParameters = null [static, protected]
Cache the application parameters for speed CAttributeCollection $appParameters.
Definition at line 86 of file YiiXLBase.php.
$_classPath [static, protected]
Initial value:
 array(
    'CXLOptions',
    'CHtml',
  )
An array of class names to search in for missing static methods.
This is a quick an dirty little polymorpher.
array $classPath
Definition at line 102 of file YiiXLBase.php.
$_clientScript = null [static, protected]
Cache the client script object for speed CClientScript $clientScript.
Definition at line 62 of file YiiXLBase.php.
$_thisApp = null [static, protected]
Cache the current app for speed CWebApplication $thisApp.
Definition at line 52 of file YiiXLBase.php.
$_thisController = null [static, protected]
Cache the current controller for speed CController $thisController.
Definition at line 72 of file YiiXLBase.php.
$_thisRequest = null [static, protected]
Cache the current request CHttpRequest $thisRequest.
Definition at line 57 of file YiiXLBase.php.
$_thisUser = null [static, protected]
Cache the user object for speed CWebUser $thisUser.
Definition at line 67 of file YiiXLBase.php.
$_uniqueIdCounter = 1000 [static, protected]
A static ID counter for generating unique names integer $_uniqueIdCounter.
Definition at line 81 of file YiiXLBase.php.
$_validLogLevels [static, protected]
array $_validLogLevels Our valid log levels based on interface definition
Definition at line 76 of file YiiXLBase.php.
const ACTION_ADMIN = 6 [inherited]
Definition at line 165 of file interfaces.php.
const ACTION_CANCEL = 998 [inherited]
Definition at line 173 of file interfaces.php.
const ACTION_CREATE = 1 [inherited]
Definition at line 160 of file interfaces.php.
const ACTION_DELETE = 5 [inherited]
Definition at line 164 of file interfaces.php.
const ACTION_EDIT = 3 [inherited]
Definition at line 162 of file interfaces.php.
const ACTION_GENERIC = 999 [inherited]
Definition at line 174 of file interfaces.php.
const ACTION_LOCK = 7 [inherited]
Definition at line 166 of file interfaces.php.
const ACTION_NONE = 0 [inherited]
Definition at line 159 of file interfaces.php.
const ACTION_PREVIEW = 996 [inherited]
Definition at line 171 of file interfaces.php.
const ACTION_RETURN = 997 [inherited]
Definition at line 172 of file interfaces.php.
const ACTION_SAVE = 4 [inherited]
Definition at line 163 of file interfaces.php.
const ACTION_UNLOCK = 8 [inherited]
Definition at line 167 of file interfaces.php.
const ACTION_VIEW = 2 [inherited]
Definition at line 161 of file interfaces.php.
const CLASS_LOG_TAG = 'yiixl.core.YiiXLBase'
Our logging tag.
Definition at line 42 of file YiiXLBase.php.
const LOG_ALERT = 1 [inherited]
Definition at line 100 of file interfaces.php.
const LOG_AUTH = 32 [inherited]
Definition at line 108 of file interfaces.php.
const LOG_AUTHPRIV = 80 [inherited]
Definition at line 110 of file interfaces.php.
const LOG_CRIT = 2 [inherited]
Definition at line 101 of file interfaces.php.
const LOG_DEBUG = 7 [inherited]
Definition at line 106 of file interfaces.php.
const LOG_EMERG = 0 [inherited]
Logging Constants.
Definition at line 99 of file interfaces.php.
const LOG_ERR = 3 [inherited]
Definition at line 102 of file interfaces.php.
const LOG_INFO = 6 [inherited]
Definition at line 105 of file interfaces.php.
const LOG_NOTICE = 5 [inherited]
Definition at line 104 of file interfaces.php.
const LOG_SYSLOG = 40 [inherited]
Definition at line 109 of file interfaces.php.
const LOG_USER = 8 [inherited]
Definition at line 107 of file interfaces.php.
const LOG_WARNING = 4 [inherited]
Definition at line 103 of file interfaces.php.
const OF_ASSOC_ARRAY = 2 [inherited]
Definition at line 143 of file interfaces.php.
const OF_HTTP = 1 [inherited]
Definition at line 142 of file interfaces.php.
const OF_JSON = 0 [inherited]
Standard output formats.
Definition at line 141 of file interfaces.php.
const OF_XML = 3 [inherited]
Definition at line 144 of file interfaces.php.
const PL_BOTTOM_LEFT = 2 [inherited]
Definition at line 152 of file interfaces.php.
const PL_BOTTOM_RIGHT = 3 [inherited]
Definition at line 153 of file interfaces.php.
const PL_TOP_LEFT = 0 [inherited]
Pager locations.
Definition at line 150 of file interfaces.php.
const PL_TOP_RIGHT = 1 [inherited]
Definition at line 151 of file interfaces.php.
The documentation for this class was generated from the following file:
YiiXLBase.php