YiiXL -- The Yii Extension Library Of Doom!: CXLApiComponent Class Reference
CXLApiComponent Class Reference
CXLApiComponent provides a convenient base class for API access.
Public Member Functions
init ()
Initialize.
addRequestMapping ($label, $parameterName=null, $required=false, $options=array(), $apiName=null, $subApiName=null)
Adds to the requestMap array.
onBeforeApiCall (CXLApiEvent $event)
Raises the onBeforeApiCall event.
beforeApiCall (CXLApiEvent $event)
Base event handler.
onAfterApiCall (CXLApiEvent $event)
Raises the onAfterApiCall event.
afterApiCall (CXLApiEvent $event)
Base event handler.
onRequestComplete (CXLApiEvent $event)
Raises the onRequestComplete event.
requestComplete (CXLApiEvent $event)
Base event handler.
getAltApiKey ()
setAltApiKey ($altApiKey)
getAppendFormat ()
setAppendFormat ($appendFormat)
getApiBaseUrl ()
setApiBaseUrl ($apiBaseUrl)
getApiKey ()
setApiKey ($apiKey)
getApiQueryName ()
setApiQueryName ($apiQueryName)
getApiToUseprotected ()
setApiToUseprotected ($apiToUseprotected)
getApiSubUrls ()
setApiSubUrls ($apiSubUrls)
getHttpMethod ()
setHttpMethod ($httpMethod)
getReturnFormat ()
setReturnFormat ($returnFormat)
getRequestData ()
setRequestData ($requestData)
getRequestMap ()
setRequestMap ($requestMap)
getRequireApiQueryName ()
setRequireApiQueryName ($requireApiQueryName)
getTestApiKey ()
setTestApiKey ($testApiKey)
getTestAltApiKey ()
setTestAltApiKey ($testAltApiKey)
getUserAgent ()
setUserAgent ($userAgent)
getLastErrorMessage ()
setLastErrorMessage ($lastErrorMessage)
getLastErrorMessageExtra ()
setLastErrorMessageExtra ($lastErrorMessageExtra)
getLastErrorCode ()
setLastErrorCode ($lastErrorCode)
getBaseUrl ()
setBaseUrl ($baseUrl)
getValidateOptions ()
setValidateOptions ($validateOptions)
getValidOptions ()
setValidOptions ($validOptions)
getValidateCallbacks ()
setValidateCallbacks ($validateCallbacks)
getValidCallbacks ()
setValidCallbacks ($validCallbacks)
getCallbacks ()
setCallbacks ($callbacks)
getExternalLibraryUrl ()
setExternalLibraryUrl ($externalLibraryUrl)
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
getOption ($key, $defaultValue=null, $unsetAfter=false)
Gets a single configuration option.
attachBehavior ($name, $behavior)
Attaches a behavior to this component.
detachBehavior ($name)
Detaches a behavior from the component.
__call ($name, $parameters)
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.components.CXLApiComponent'
Our logging tag.
Protected Member Functions
makeRequest ($subType= '/', $requestData=null, $requestMethod= 'GET')
Makes the actual HTTP request based on settings.
Static Protected Member Functions
static _getCallerObject ($instanceFilter=null)
Walks the backtrace to find the calling object.
Protected Attributes
$_apiKey
$_altApiKey
$_appendFormat
$_apiBaseUrl
$_apiQueryName
$_apiToUseprotected
$_apiSubUrls
$_httpMethod
$_returnFormat
$_payload
$_requestMap
$_requireApiQueryName
$_testApiKey
$_testAltApiKey
$_userAgent = 'YiiXL; (+http://www.pogostick.com/yiixl)'
$_lastErrorMessage
$_lastErrorMessageExtra
$_lastErrorCode
$_baseUrl
$_validateOptions = true
$_validOptions = array()
$_validateCallbacks = true
$_validCallbacks = array()
$_callbacks = array()
$_externalLibraryUrl = '/'
$_debugLevel = false
$_options
$_behaviorMethods
Detailed Description
CXLApiComponent provides a convenient base class for API access.
Introduces three new events:
onBeforeApiCall onAfterApiCall onRequestComplete
Each are called respectively and pass the handler a CXLApiEvent object with details of the call.
Definition at line 29 of file CXLApiComponent.php.
Member Function Documentation
__call ($ name, $ parameters) [inherited]
Parameters:
string $name
array $parameters
Returns:
mixed
Definition at line 190 of file CXLComponent.php.
References YiiXLBase::smartCall().
static _getCallerObject ($ instanceFilter = null) [static, protected, inherited]
Walks the backtrace to find the calling object.
Parameters:
string $instanceFilter Only return objects of this instance
Definition at line 213 of file CXLComponent.php.
References YiiXLBase::o().
addRequestMapping ($ label, $ parameterName = null, $ required = false, $ options = array(), $ apiName = null, $ subApiName = null)
Adds to the requestMap array.
Parameters:
string $label The "friendly" name for consumers
string $parameterName The name of the API variable, if null, $label
bool $required
array $options
string $apiName
string $subApiName
Returns:
bool True if operation succeeded
See also:
makeMapItem
makeMapArray
Definition at line 180 of file CXLApiComponent.php.
afterApiCall (CXLApiEvent $ event)
Base event handler.
Parameters:
CXLApiEvent $event
Returns:
boolean
Definition at line 409 of file CXLApiComponent.php.
attachBehavior ($ name, $ behavior) [inherited]
Attaches a behavior to this component.
Calls the Yii implementation of this method, then injects the behaviors methods into our class.
Parameters:
string $name The behavior's name. It should uniquely identify this behavior.
mixed $behavior the behavior configuration. This is passed as the first parameter to YiiBase::createComponent to create the behavior object.
Returns:
IBehavior the behavior object
Definition at line 147 of file CXLComponent.php.
beforeApiCall (CXLApiEvent $ event)
Base event handler.
Parameters:
CXLApiEvent $event
Returns:
boolean
Definition at line 389 of file CXLApiComponent.php.
detachBehavior ($ name) [inherited]
Detaches a behavior from the component.
The behavior's IBehavior::detach method will be invoked.
Parameters:
string $name the behavior's name. It uniquely identifies the behavior.
Returns:
IBehavior the detached behavior. Null if the behavior does not exist.
Since:
1.0.2
Todo:
Implement un-importing methods
Definition at line 176 of file CXLComponent.php.
getAltApiKey ()
Definition at line 438 of file CXLApiComponent.php.
getApiBaseUrl ()
Definition at line 458 of file CXLApiComponent.php.
getApiKey ()
Definition at line 468 of file CXLApiComponent.php.
getApiQueryName ()
Definition at line 478 of file CXLApiComponent.php.
getApiSubUrls ()
Definition at line 498 of file CXLApiComponent.php.
getApiToUseprotected ()
Definition at line 488 of file CXLApiComponent.php.
getAppendFormat ()
Definition at line 448 of file CXLApiComponent.php.
getBaseUrl ()
Definition at line 618 of file CXLApiComponent.php.
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 94 of file CXLComponent.php.
Referenced by YiiXLBase::smartCall().
getCallbacks ()
Definition at line 668 of file CXLApiComponent.php.
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 67 of file CXLComponent.php.
getExternalLibraryUrl ()
Definition at line 678 of file CXLApiComponent.php.
getHttpMethod ()
Definition at line 508 of file CXLApiComponent.php.
getLastErrorCode ()
Definition at line 608 of file CXLApiComponent.php.
getLastErrorMessage ()
Definition at line 588 of file CXLApiComponent.php.
getLastErrorMessageExtra ()
Definition at line 598 of file CXLApiComponent.php.
getOption ($ key, $ defaultValue = null, $ unsetAfter = false) [inherited]
Gets a single configuration option.
Returns:
mixed
Definition at line 132 of file CXLComponent.php.
References YiiXLBase::o().
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 85 of file CXLComponent.php.
getRequestData ()
Definition at line 528 of file CXLApiComponent.php.
getRequestMap ()
Definition at line 538 of file CXLApiComponent.php.
getRequireApiQueryName ()
Definition at line 548 of file CXLApiComponent.php.
getReturnFormat ()
Definition at line 518 of file CXLApiComponent.php.
getTestAltApiKey ()
Definition at line 568 of file CXLApiComponent.php.
getTestApiKey ()
Definition at line 558 of file CXLApiComponent.php.
getUserAgent ()
Definition at line 578 of file CXLApiComponent.php.
getValidateCallbacks ()
Definition at line 648 of file CXLApiComponent.php.
getValidateOptions ()
Definition at line 628 of file CXLApiComponent.php.
getValidCallbacks ()
Definition at line 658 of file CXLApiComponent.php.
getValidOptions ()
Definition at line 638 of file CXLApiComponent.php.
init ()
Initialize.
Definition at line 152 of file CXLApiComponent.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 104 of file CXLComponent.php.
makeRequest ($ subType = '/', $ requestData = null, $ requestMethod = 'GET') [protected]
Makes the actual HTTP request based on settings.
Parameters:
string $subType
array $requestData
Returns:
string
Definition at line 227 of file CXLApiComponent.php.
References $_payload, $_requestMap, onAfterApiCall(), onBeforeApiCall(), and onRequestComplete().
onAfterApiCall (CXLApiEvent $ event)
Raises the onAfterApiCall event.
$event contains "raw" return data
Parameters:
CXLApiEvent $event
Definition at line 399 of file CXLApiComponent.php.
Referenced by makeRequest().
onBeforeApiCall (CXLApiEvent $ event)
Raises the onBeforeApiCall event.
Parameters:
CXLApiEvent $event
Definition at line 379 of file CXLApiComponent.php.
Referenced by makeRequest().
onRequestComplete (CXLApiEvent $ event)
Raises the onRequestComplete event.
$event contains "processed" return data (if applicable)
Parameters:
CXLApiEvent $event
Definition at line 419 of file CXLApiComponent.php.
Referenced by makeRequest().
requestComplete (CXLApiEvent $ event)
Base event handler.
Parameters:
CXLApiEvent $event
Returns:
boolean
Definition at line 429 of file CXLApiComponent.php.
setAltApiKey ($ altApiKey)
Definition at line 443 of file CXLApiComponent.php.
setApiBaseUrl ($ apiBaseUrl)
Definition at line 463 of file CXLApiComponent.php.
setApiKey ($ apiKey)
Definition at line 473 of file CXLApiComponent.php.
setApiQueryName ($ apiQueryName)
Definition at line 483 of file CXLApiComponent.php.
setApiSubUrls ($ apiSubUrls)
Definition at line 503 of file CXLApiComponent.php.
setApiToUseprotected ($ apiToUseprotected)
Definition at line 493 of file CXLApiComponent.php.
setAppendFormat ($ appendFormat)
Definition at line 453 of file CXLApiComponent.php.
setBaseUrl ($ baseUrl)
Definition at line 623 of file CXLApiComponent.php.
setCallbacks ($ callbacks)
Definition at line 673 of file CXLApiComponent.php.
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Implements IXLComponent.
Definition at line 76 of file CXLComponent.php.
setExternalLibraryUrl ($ externalLibraryUrl)
Definition at line 683 of file CXLApiComponent.php.
setHttpMethod ($ httpMethod)
Definition at line 513 of file CXLApiComponent.php.
setLastErrorCode ($ lastErrorCode)
Definition at line 613 of file CXLApiComponent.php.
setLastErrorMessage ($ lastErrorMessage)
Definition at line 593 of file CXLApiComponent.php.
setLastErrorMessageExtra ($ lastErrorMessageExtra)
Definition at line 603 of file CXLApiComponent.php.
setRequestData ($ requestData)
Definition at line 533 of file CXLApiComponent.php.
setRequestMap ($ requestMap)
Definition at line 543 of file CXLApiComponent.php.
setRequireApiQueryName ($ requireApiQueryName)
Definition at line 553 of file CXLApiComponent.php.
setReturnFormat ($ returnFormat)
Definition at line 523 of file CXLApiComponent.php.
setTestAltApiKey ($ testAltApiKey)
Definition at line 573 of file CXLApiComponent.php.
setTestApiKey ($ testApiKey)
Definition at line 563 of file CXLApiComponent.php.
setUserAgent ($ userAgent)
Definition at line 583 of file CXLApiComponent.php.
setValidateCallbacks ($ validateCallbacks)
Definition at line 653 of file CXLApiComponent.php.
setValidateOptions ($ validateOptions)
Definition at line 633 of file CXLApiComponent.php.
setValidCallbacks ($ validCallbacks)
Definition at line 663 of file CXLApiComponent.php.
setValidOptions ($ validOptions)
Definition at line 643 of file CXLApiComponent.php.
Field Documentation
$_altApiKey [protected]
Definition at line 51 of file CXLApiComponent.php.
$_apiBaseUrl [protected]
Definition at line 59 of file CXLApiComponent.php.
$_apiKey [protected]
Definition at line 47 of file CXLApiComponent.php.
$_apiQueryName [protected]
Definition at line 63 of file CXLApiComponent.php.
$_apiSubUrls [protected]
Definition at line 71 of file CXLApiComponent.php.
$_apiToUseprotected [protected]
Definition at line 67 of file CXLApiComponent.php.
$_appendFormat [protected]
Definition at line 55 of file CXLApiComponent.php.
$_baseUrl [protected]
Definition at line 119 of file CXLApiComponent.php.
$_behaviorMethods [protected, inherited]
Definition at line 57 of file CXLComponent.php.
$_callbacks = array() [protected]
Definition at line 139 of file CXLApiComponent.php.
$_debugLevel = false [protected, inherited]
Definition at line 47 of file CXLComponent.php.
$_externalLibraryUrl = '/' [protected]
Definition at line 143 of file CXLApiComponent.php.
$_httpMethod [protected]
Definition at line 75 of file CXLApiComponent.php.
$_lastErrorCode [protected]
Definition at line 115 of file CXLApiComponent.php.
$_lastErrorMessage [protected]
Definition at line 107 of file CXLApiComponent.php.
$_lastErrorMessageExtra [protected]
Definition at line 111 of file CXLApiComponent.php.
$_options [protected, inherited]
Reimplemented in CXLConfig.
Definition at line 52 of file CXLComponent.php.
$_payload [protected]
Definition at line 83 of file CXLApiComponent.php.
Referenced by makeRequest().
$_requestMap [protected]
Definition at line 87 of file CXLApiComponent.php.
Referenced by makeRequest().
$_requireApiQueryName [protected]
Definition at line 91 of file CXLApiComponent.php.
$_returnFormat [protected]
Definition at line 79 of file CXLApiComponent.php.
$_testAltApiKey [protected]
Definition at line 99 of file CXLApiComponent.php.
$_testApiKey [protected]
Definition at line 95 of file CXLApiComponent.php.
$_userAgent = 'YiiXL; (+http://www.pogostick.com/yiixl)' [protected]
Definition at line 103 of file CXLApiComponent.php.
$_validateCallbacks = true [protected]
Definition at line 131 of file CXLApiComponent.php.
$_validateOptions = true [protected]
Definition at line 123 of file CXLApiComponent.php.
$_validCallbacks = array() [protected]
Definition at line 135 of file CXLApiComponent.php.
$_validOptions = array() [protected]
Definition at line 127 of file CXLApiComponent.php.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLApiComponent'
Our logging tag.
Reimplemented from CXLComponent.
Definition at line 38 of file CXLApiComponent.php.
The documentation for this class was generated from the following file:
CXLApiComponent.php