YiiXL -- The Yii Extension Library Of Doom!: CXLController Class Reference
CXLController Class Reference
CXLController Provides filtered access to resources.
Public Member Functions
init ()
Initialize the controller.
actions ()
How about a default action that displays static pages? Huh? Huh?
genericAction ($actionId, $model=null, $extraParameters=array(), $modelVariableName= 'model', $flashMessageKey=null, $flashMessageValue=null, $flashMessageDefaultValue=null)
A generic action that renders a page and passes in the model.
loadCurrentModel ($id=null)
Returns the data model based on the primary key given in the GET variable.
missingAction ($actionId=null)
Provide automatic missing action mapping...
actionError ()
Our error handler...
getRequest ()
Convenience access to Yii request.
beforeAction ($action)
See if there are any commands that need processing.
newRender ($viewName, $viewData=null, $returnString=false)
Renders a view with a layout.
renderPartial ($view, $data=null, $return=false, $processOutput=false)
Renders a view.
setStandardFormOptions ($model, $optionList=array())
Creates a standard form options array and loads page niceties.
setContentType ($contentType, $noLayout=true)
Sets the content type for this page to the specified MIME type.
setViewNavigationOptions (&$options=array())
Sets the standard page navigation options (title, crumbs, menu, etc.
getIsPostRequest ()
Convenience access to isPostRequest.
getIsAjaxRequest ()
Convenience access to isAjaxRequest.
getAppBaseUrl ()
Returns the base url of the current app.
getMenu ()
setMenu ($value)
getBreadcrumbs ()
setBreadcrumbs ($value)
getPageHeading ()
setPageHeading ($value)
getActionMethodPrefix ()
setActionMethodPrefix ($value)
getCurrentModel ()
getModelClass ()
getContentTemplate ()
setContentTemplate ($value)
getAutoFindLayout ()
setAutoFindLayout ($value)
getAutoFindAction ()
setAutoFindAction ($value)
getAdminCommandMap ()
setAdminCommandMap ($value)
addCommandToMap ($key, $value=null, $property=null)
getPortletActions ()
setPortletActions ($value)
addPortletAction ($sName, $arCallback)
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.components.CXLController'
Our logging tag string.
const PAGE_SIZE = 10
The number of items to display per page.
const COMMAND_FIELD_NAME = '__yxl'
The name of our command form field.
const SEARCH_HELP_TEXT = 'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>or <b>=</b>) at the beginning of each search value to specify how the comparison should be done.'
Standard search text for rendering.
const ACCESS_TO_NONE = -1
const ACCESS_TO_ANY = 0
const ACCESS_TO_GUEST = 1
const ACCESS_TO_AUTH = 2
const ACCESS_TO_ADMIN = 3
const ACCESS_TO_ADMIN_LEVEL_0 = 3
const ACCESS_TO_ADMIN_LEVEL_1 = 4
const ACCESS_TO_ADMIN_LEVEL_2 = 5
Protected Member Functions
setCurrentModel ($value)
setModelClass ($value)
getViewData ()
setViewData ($value)
getExtraViewDataList ()
setExtraViewDataList ($value)
getExtraViewDataPrefix ()
setExtraViewDataPrefix ($value)
_processCommand ($arData=array(), $sIndexName=self::COMMAND_FIELD_NAME)
Executes any commands Maps to CXLController::commandMap and calls the appropriate method.
_saveCurrentModel (&$model, $arData=array(), $sRedirectAction= 'show', $bAttributesSet=false, $sModelName=null, $sSuccessMessage=null, $bNoCommit=false, $bSafeOnly=false)
Saves the data in the model.
_saveTransactionCurrentModel (&$model, $arData=array(), $bAttributesSet=false, $sSuccessMessage=null)
_loadPaged ($bSort=false, $oCriteria=null)
Loads a page of models.
_genericModelLoad ($sMethod, &$oCrit=null, $arScope=array(), $arOptions=array())
Loads a model(s) based on criteria and scopes.
_load ($id=null)
_loadAll (&$oCrit=null)
Loads all data using supplied criteria.
_loadCount (&$oCrit=null)
Returns the count of rows that match the supplied criteria.
_getModelLoadString ($arScope=array(), $arOptions=array())
Builds a string suitable for eval.
_pushAction ($action)
Pushes an action onto the action queue.
_popAction ()
Retrieves the latest pushed action.
_addViewData ($variableName, $variableData=null)
Pushes a variable onto the view data stack.
_clearSearchCriteria ()
Clears the current search criteria.
_ajaxReturn ($payload=false, $encode=false, $encodeOptions=ENT_NOQUOTES)
Turns off the layout, echos the JSON encoded version of data and returns.
Protected Attributes
$_menu = array()
$_breadcrumbs = array()
$_pageHeading
$_actionMethodPrefix = 'action'
$_currentModel = null
$_modelClass = null
$_contentTemplate = null
$_autoFindLayout = true
$_autoFindAction = true
$_adminCommandMap = array()
$_actionStack = array()
$_portletActions = array()
$_viewData = array()
$_extraViewDataList = array()
$_extraViewDataPrefix = '_'
Detailed Description
CXLController Provides filtered access to resources.
Definition at line 21 of file CXLController.php.
Member Function Documentation
_addViewData ($ variableName, $ variableData = null) [protected]
Pushes a variable onto the view data stack.
Parameters:
string $variableName
mixed $variableData
Definition at line 1142 of file CXLController.php.
_ajaxReturn ($ payload = false, $ encode = false, $ encodeOptions = ENT_NOQUOTES) [protected]
Turns off the layout, echos the JSON encoded version of data and returns.
Optionally encoding HTML characters.
Parameters:
array $payload The response data
boolean $encode If true, response is run through htmlspecialchars()
integer $encodeOptions Options for htmlspecialchars. Defaults to ENT_NOQUOTES
Definition at line 1165 of file CXLController.php.
_clearSearchCriteria () [protected]
Clears the current search criteria.
Returns:
null
Definition at line 1151 of file CXLController.php.
_genericModelLoad ($ sMethod, &$ oCrit = null, $ arScope = array(), $ arOptions = array()) [protected]
Loads a model(s) based on criteria and scopes.
Parameters:
string The method to append
CDbCriteria The criteria for the lookup
array Scopes to apply to this request
array Options for the data load
Returns:
CActiveRecord|array
Definition at line 1064 of file CXLController.php.
References _getModelLoadString().
Referenced by _load(), _loadAll(), and _loadCount().
_getModelLoadString ($ arScope = array(), $ arOptions = array()) [protected]
Builds a string suitable for eval.
The verb is intentionally not appeneded.
Parameters:
array $arScope
Returns:
string
Todo:
Will be deprecated after upgrade to PHP v5.3
Definition at line 1111 of file CXLController.php.
Referenced by _genericModelLoad().
_load ($ id = null) [protected]
Definition at line 1076 of file CXLController.php.
References _genericModelLoad().
Referenced by loadCurrentModel().
_loadAll (&$ oCrit = null) [protected]
Loads all data using supplied criteria.
Parameters:
CDbCriteria $oCrit
Returns:
array Array of CActiveRecord
Todo:
When using PHP v5.3, eval will no longer be needed
Definition at line 1087 of file CXLController.php.
References _genericModelLoad().
Referenced by _loadPaged().
_loadCount (&$ oCrit = null) [protected]
Returns the count of rows that match the supplied criteria.
Parameters:
CDbCriteria $oCrit
Returns:
integer The number of rows
Definition at line 1098 of file CXLController.php.
References _genericModelLoad().
Referenced by _loadPaged().
_loadPaged ($ bSort = false, $ oCriteria = null) [protected]
Loads a page of models.
Parameters:
boolean Whether or not to apply a sort. Defaults to false
Returns:
array Element 0 is the results of the find. Element 1 is the pagination object
Definition at line 1033 of file CXLController.php.
References _loadAll(), _loadCount(), YiiXLBase::nvl(), and YiiXLBase::o().
_popAction () [protected]
Retrieves the latest pushed action.
Returns:
CAction
Definition at line 1131 of file CXLController.php.
_processCommand ($ arData = array(), $ sIndexName = self::COMMAND_FIELD_NAME) [protected]
Executes any commands Maps to CXLController::commandMap and calls the appropriate method.
Returns:
mixed
Definition at line 949 of file CXLController.php.
References getIsPostRequest(), and YiiXLBase::o().
Referenced by beforeAction().
_pushAction ($ action) [protected]
Pushes an action onto the action queue.
Parameters:
CAction $action
Definition at line 1122 of file CXLController.php.
_saveCurrentModel (&$ model, $ arData = array(), $ sRedirectAction = 'show', $ bAttributesSet = false, $ sModelName = null, $ sSuccessMessage = null, $ bNoCommit = false, $ bSafeOnly = false) [protected]
Saves the data in the model.
Parameters:
CModel $model The model to save
array $arData The array of data to merge with the model
string $sRedirectAction Where to redirect after a successful save
boolean $bAttributesSet If true, attributes will not be set from $arData
string $sModelName Optional model name
string $sSuccessMessage Flash message to set if successful
boolean $bNoCommit If true, transaction will not be committed
Returns:
boolean
Definition at line 986 of file CXLController.php.
References YiiXLBase::nvl().
Referenced by _saveTransactionCurrentModel().
_saveTransactionCurrentModel (&$ model, $ arData = array(), $ bAttributesSet = false, $ sSuccessMessage = null) [protected]
Definition at line 1022 of file CXLController.php.
References _saveCurrentModel().
actionError ()
Our error handler...
Definition at line 275 of file CXLController.php.
References YiiXLBase::_gco().
actions ()
How about a default action that displays static pages? Huh? Huh?
In your configuration file, configure the urlManager as follows:
'urlManager' => array('urlFormat' => 'path', 'showScriptName' => false, 'rules' => array(... all your rules should be first ... // Add this as the last line in your rules. '<view:+>' => 'default/_static',),
The above assumes your default controller is DefaultController. If is different simply change the route above (default/_static) to your default route.
Finally, create a directory under your default controller's view path:
/path/to/your/app/protected/views/default/_static
Place your static files in there, for example:
/path/to/your/app/protected/views/default/_static/aboutUs.php /path/to/your/app/protected/views/default/_static/contactUs.php /path/to/your/app/protected/views/default/_static/help.php
Returns:
array
Definition at line 187 of file CXLController.php.
beforeAction ($ action)
See if there are any commands that need processing.
Parameters:
CAction $action
Returns:
boolean
Definition at line 307 of file CXLController.php.
References _processCommand().
genericAction ($ actionId, $ model = null, $ extraParameters = array(), $ modelVariableName = 'model', $ flashMessageKey = null, $ flashMessageValue = null, $ flashMessageDefaultValue = null)
A generic action that renders a page and passes in the model.
Parameters:
string The action id
CModel The model
array Extra parameters to pass to the view
string The name of the variable to pass to the view. Defaults to 'model'
Definition at line 207 of file CXLController.php.
References YiiXLBase::_sf(), and loadCurrentModel().
getRequest ()
Convenience access to Yii request.
Definition at line 297 of file CXLController.php.
References YiiXLBase::_gr().
init ()
Initialize the controller.
Definition at line 131 of file CXLController.php.
References YiiXLBase::_a(), YiiXLBase::_gbp(), YiiXLBase::_gcu(), and YiiXLBase::o().
loadCurrentModel ($ id = null)
Returns the data model based on the primary key given in the GET variable.
If the data model is not found, an HTTP exception will be raised.
Parameters:
integer the primary key value. Defaults to null, meaning using the 'id' GET variable
Exceptions:
CHttpException
Definition at line 230 of file CXLController.php.
References _load(), YiiXLBase::o(), and setModelClass().
Referenced by genericAction().
missingAction ($ actionId = null)
Provide automatic missing action mapping...
Also handles a theme change request from any portlets
Parameters:
string $actionId
Definition at line 255 of file CXLController.php.
newRender ($ viewName, $ viewData = null, $ returnString = false)
Renders a view with a layout.
This method first calls renderPartial to render the view (called content view). It then renders the layout view which may embed the content view at appropriate place. In the layout view, the content view rendering result can be accessed via variable $content. At the end, it calls processOutput to insert scripts and dynamic contents if they are available.
By default, the layout view script is "protected/views/layouts/main.php". This may be customized by changing layout.
Parameters:
string name of the view to be rendered. See getViewFile for details about how the view script is resolved.
array data to be extracted into PHP variables and made available to the view script
boolean whether the rendering result should be returned instead of being displayed to end users.
Returns:
string the rendering result. Null if the rendering result is not required.
See also:
renderPartial
getLayoutFile
Definition at line 336 of file CXLController.php.
References renderPartial().
renderPartial ($ view, $ data = null, $ return = false, $ processOutput = false)
Renders a view.
The named view refers to a PHP script (resolved via getViewFile) that is included by this method. If $data is an associative array, it will be extracted as PHP variables and made available to the script.
This method differs from render() in that it does not apply a layout to the rendered result. It is thus mostly used in rendering a partial view, or an AJAX response.
This override adds the current user to the data automatically in the $_currentUser variable
Parameters:
string name of the view to be rendered. See getViewFile for details about how the view script is resolved.
array data to be extracted into PHP variables and made available to the view script
boolean whether the rendering result should be returned instead of being displayed to end users
boolean whether the rendering result should be postprocessed using processOutput.
Returns:
string the rendering result. Null if the rendering result is not required.
Exceptions:
CException if the view does not exist
See also:
getViewFile
processOutput
render
Definition at line 381 of file CXLController.php.
Referenced by newRender(), and setStandardFormOptions().
setContentType ($ contentType, $ noLayout = true)
Sets the content type for this page to the specified MIME type.
Parameters:
<type> $contentType The MIME type to set
boolean $noLayout If true, the layout for this page is set to false
Definition at line 531 of file CXLController.php.
setStandardFormOptions ($ model, $ optionList = array())
Creates a standard form options array and loads page niceties.
Parameters:
CModel $model
string|array If a string is passed in, it is used as the title.
Returns:
array
Definition at line 425 of file CXLController.php.
References YiiXLBase::_gan(), YiiXLBase::_gf(), YiiXLBase::_rs(), YiiXLBase::_ss(), YiiXLBase::o(), renderPartial(), and setViewNavigationOptions().
setViewNavigationOptions (&$ options = array())
Sets the standard page navigation options (title, crumbs, menu, etc.
)
Parameters:
array $options
Definition at line 541 of file CXLController.php.
References YiiXLBase::_gan(), and YiiXLBase::o().
Referenced by setStandardFormOptions().
Field Documentation
$_actionMethodPrefix = 'action' [protected]
Definition at line 60 of file CXLController.php.
$_actionStack = array() [protected]
Definition at line 100 of file CXLController.php.
$_adminCommandMap = array() [protected]
Definition at line 95 of file CXLController.php.
$_autoFindAction = true [protected]
Definition at line 89 of file CXLController.php.
$_autoFindLayout = true [protected]
Definition at line 83 of file CXLController.php.
$_breadcrumbs = array() [protected]
Definition at line 49 of file CXLController.php.
$_contentTemplate = null [protected]
Definition at line 77 of file CXLController.php.
$_currentModel = null [protected]
Definition at line 65 of file CXLController.php.
$_extraViewDataList = array() [protected]
Definition at line 116 of file CXLController.php.
$_extraViewDataPrefix = '_' [protected]
Definition at line 122 of file CXLController.php.
$_menu = array() [protected]
Definition at line 41 of file CXLController.php.
$_modelClass = null [protected]
Definition at line 71 of file CXLController.php.
$_pageHeading [protected]
Definition at line 55 of file CXLController.php.
$_portletActions = array() [protected]
Definition at line 105 of file CXLController.php.
$_viewData = array() [protected]
Definition at line 110 of file CXLController.php.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLController'
Our logging tag string.
Definition at line 31 of file CXLController.php.
The documentation for this class was generated from the following file:
CXLController.php