YiiXL -- The Yii Extension Library Of Doom!: CXLLiveLogRoute Class Reference
CXLLiveLogRoute Class Reference
CXLLiveLogRoute.
Public Member Functions
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets configuration options.
getExcludeCategories ()
setExcludeCategories ($value)
getCategoryWidth ()
Get the minimum width of the category column in the log output.
setCategoryWidth ($value)
Set the minimum width of the category column in the log output.
collectLogs ($logger, $processLogs=false)
Retrieves filtered log messages from logger for further processing.
loadOptions ($options=array())
Loads the configuration options.
getBehaviorMethods ()
Gets behavior methods.
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.components.logging.CXLLiveLogRoute'
Our logging tag.
Protected Member Functions
processLogs ($logs=array())
Writes log messages in files.
formatLogMessage ($message, $level= 'I', $category=null, $time=null)
Formats a log message given different fields.
Protected Attributes
$_debugLevel = false
$_options
$_excludeCategories = array()
$_categoryWidth = 40
Detailed Description
CXLLiveLogRoute.
Definition at line 20 of file CXLLiveLogRoute.php.
Member Function Documentation
collectLogs ($ logger, $ processLogs = false)
Retrieves filtered log messages from logger for further processing.
Parameters:
CLogger $logger logger instance
boolean $processLogs whether to process the logs after they are collected from the logger. ALWAYS TRUE NOW!
Definition at line 122 of file CXLLiveLogRoute.php.
formatLogMessage ($ message, $ level = 'I', $ category = null, $ time = null) [protected]
Formats a log message given different fields.
Parameters:
string $message message content
integer $level message level
string $category message category
integer $time timestamp
Returns:
string formatted message
Definition at line 192 of file CXLLiveLogRoute.php.
Referenced by processLogs().
getBehaviorMethods () [inherited]
Gets behavior methods.
Needed to implement lightweight helper classes
Returns:
array
Implemented in CXLActiveRecordBehavior, CXLBehavior, CXLComponent, and CXLWidget.
getCategoryWidth ()
Get the minimum width of the category column in the log output.
Returns:
integer
Definition at line 99 of file CXLLiveLogRoute.php.
getDebugLevel ()
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 62 of file CXLLiveLogRoute.php.
getExcludeCategories ()
Definition at line 85 of file CXLLiveLogRoute.php.
getOptions ()
Gets configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 80 of file CXLLiveLogRoute.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array $options
Returns:
CXLComponent
Implemented in CXLActiveRecordBehavior, CXLBehavior, CXLComponent, and CXLWidget.
Referenced by CXLOptions::loadConfiguration().
processLogs ($ logs = array()) [protected]
Writes log messages in files.
Parameters:
array $logs list of log messages
Use error_log facility to write out log entry
Definition at line 135 of file CXLLiveLogRoute.php.
References formatLogMessage().
setCategoryWidth ($ value)
Set the minimum width of the category column in the log output.
Returns:
integer
Definition at line 108 of file CXLLiveLogRoute.php.
setDebugLevel ($ value = false)
Sets the debug level.
Parameters:
integer The new debug level
Implements IXLComponent.
Definition at line 71 of file CXLLiveLogRoute.php.
setExcludeCategories ($ value)
Definition at line 90 of file CXLLiveLogRoute.php.
Field Documentation
$_categoryWidth = 40 [protected]
Definition at line 52 of file CXLLiveLogRoute.php.
$_debugLevel = false [protected]
Definition at line 38 of file CXLLiveLogRoute.php.
$_excludeCategories = array() [protected]
Definition at line 47 of file CXLLiveLogRoute.php.
$_options [protected]
Definition at line 42 of file CXLLiveLogRoute.php.
const CLASS_LOG_TAG = 'yiixl.core.components.logging.CXLLiveLogRoute'
Our logging tag.
Definition at line 29 of file CXLLiveLogRoute.php.
The documentation for this class was generated from the following file:
CXLLiveLogRoute.php