YiiXL -- The Yii Extension Library Of Doom!: CXLRestConsumerComponent Class Reference
CXLRestConsumerComponent Class Reference
CXLRestConsumerComponent.
Public Member Functions
init ()
Preinitialize.
onBeforeApiCall ($event)
Raises the onBeforeApiCall event.
beforeApiCall ($event)
Base event handler.
onAfterApiCall ($event)
Raises the onAfterApiCall event.
afterApiCall ($event)
Base event handler.
onRequestComplete ($event)
Raises the onRequestComplete event.
requestComplete ($event)
Base event handler.
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
getOption ($key, $defaultValue=null, $unsetAfter=false)
Gets a single configuration option.
attachBehavior ($name, $behavior)
Attaches a behavior to this component.
detachBehavior ($name)
Detaches a behavior from the component.
__call ($name, $parameters)
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.components.CXLRestConsumerComponent'
Our logging tag.
Protected Member Functions
makeMapArray ($apiName, $subApiName=null, array $apiMap, $setRequestMap=true)
Creates an array for requestMap.
makeMapItem ($itemLabel, $parameterName=null, $required=false, $options=array(), array &$target=null)
S Creates an entry for requestMap and inserts it into the array.
Static Protected Member Functions
static _getCallerObject ($instanceFilter=null)
Walks the backtrace to find the calling object.
Protected Attributes
$_apiKey
$_altApiKey
$_appendFormat
$_apiBaseUrl
$_apiQueryName
$_apiToUseprotected
$_apiSubUrls
$_httpMethod
$_returnFormat
$_payload
$_requestMap
$_requireApiQueryName
$_testApiKey
$_testAltApiKey
$_userAgent = 'YiiXL; (+http://github.com/Pogostick/YiiXL)'
$_lastErrorMessage
$_lastErrorMessageExtra
$_lastErrorCode
$_baseUrl
$_validateOptions = true
$_validOptions = array()
$_validateCallbacks = true
$_validCallbacks = array()
$_callbacks = array()
$_externalLibraryUrl = '/'
$_debugLevel = false
$_options
$_behaviorMethods
Detailed Description
CXLRestConsumerComponent.
Introduces three new events:
onBeforeRestCall onAfterRestCall onRequestComplete
Definition at line 26 of file CXLRestConsumerComponent.php.
Member Function Documentation
__call ($ name, $ parameters) [inherited]
Parameters:
string $name
array $parameters
Returns:
mixed
Definition at line 190 of file CXLComponent.php.
References YiiXLBase::smartCall().
static _getCallerObject ($ instanceFilter = null) [static, protected, inherited]
Walks the backtrace to find the calling object.
Parameters:
string $instanceFilter Only return objects of this instance
Definition at line 213 of file CXLComponent.php.
References YiiXLBase::o().
afterApiCall ($ event)
Base event handler.
Parameters:
CPSApiEvent $event
Definition at line 260 of file CXLRestConsumerComponent.php.
attachBehavior ($ name, $ behavior) [inherited]
Attaches a behavior to this component.
Calls the Yii implementation of this method, then injects the behaviors methods into our class.
Parameters:
string $name The behavior's name. It should uniquely identify this behavior.
mixed $behavior the behavior configuration. This is passed as the first parameter to YiiBase::createComponent to create the behavior object.
Returns:
IBehavior the behavior object
Definition at line 147 of file CXLComponent.php.
beforeApiCall ($ event)
Base event handler.
Parameters:
CPSApiEvent $event
Definition at line 243 of file CXLRestConsumerComponent.php.
detachBehavior ($ name) [inherited]
Detaches a behavior from the component.
The behavior's IBehavior::detach method will be invoked.
Parameters:
string $name the behavior's name. It uniquely identifies the behavior.
Returns:
IBehavior the detached behavior. Null if the behavior does not exist.
Since:
1.0.2
Todo:
Implement un-importing methods
Definition at line 176 of file CXLComponent.php.
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 94 of file CXLComponent.php.
Referenced by YiiXLBase::smartCall().
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 67 of file CXLComponent.php.
getOption ($ key, $ defaultValue = null, $ unsetAfter = false) [inherited]
Gets a single configuration option.
Returns:
mixed
Definition at line 132 of file CXLComponent.php.
References YiiXLBase::o().
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 85 of file CXLComponent.php.
init ()
Preinitialize.
Definition at line 149 of file CXLRestConsumerComponent.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 104 of file CXLComponent.php.
makeMapArray ($ apiName, $ subApiName = null, array $ apiMap, $ setRequestMap = true) [protected]
Creates an array for requestMap.
Parameters:
array $apiMap The map of items to insert into the array. Format is the same as makeMapItem
bool $setRequestMap If false, will NOT insert constructed array into requestMap
Returns:
array Returns the constructed array item ready to insert into your requestMap
See also:
makeMapItem
Definition at line 172 of file CXLRestConsumerComponent.php.
References makeMapItem().
makeMapItem ($ itemLabel, $ parameterName = null, $ required = false, $ options = array(), array &$ target = null) [protected]
S Creates an entry for requestMap and inserts it into the array.
Parameters:
string $itemLabel The label or friendly name of this map item
string $parameterName The actual parameter name to send to API. If not specified, will default to $itemLabel
bool $required Set to true if the parameter is required
array $options If supplied, will merge with generated options
array $target If supplied, will insert into array
Returns:
array Returns the constructed array item ready to insert into your requestMap
Definition at line 206 of file CXLRestConsumerComponent.php.
Referenced by makeMapArray().
onAfterApiCall ($ event)
Raises the onAfterApiCall event.
$event contains "raw" return data
Parameters:
CPSApiEvent $event
Definition at line 251 of file CXLRestConsumerComponent.php.
onBeforeApiCall ($ event)
Raises the onBeforeApiCall event.
Parameters:
CPSApiEvent $event
Definition at line 234 of file CXLRestConsumerComponent.php.
onRequestComplete ($ event)
Raises the onRequestComplete event.
$event contains "processed" return data (if applicable)
Parameters:
CPSApiEvent $event
Definition at line 268 of file CXLRestConsumerComponent.php.
requestComplete ($ event)
Base event handler.
Parameters:
CPSApiEvent $event
Definition at line 277 of file CXLRestConsumerComponent.php.
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Implements IXLComponent.
Definition at line 76 of file CXLComponent.php.
Field Documentation
$_altApiKey [protected]
Definition at line 48 of file CXLRestConsumerComponent.php.
$_apiBaseUrl [protected]
Definition at line 56 of file CXLRestConsumerComponent.php.
$_apiKey [protected]
Definition at line 44 of file CXLRestConsumerComponent.php.
$_apiQueryName [protected]
Definition at line 60 of file CXLRestConsumerComponent.php.
$_apiSubUrls [protected]
Definition at line 68 of file CXLRestConsumerComponent.php.
$_apiToUseprotected [protected]
Definition at line 64 of file CXLRestConsumerComponent.php.
$_appendFormat [protected]
Definition at line 52 of file CXLRestConsumerComponent.php.
$_baseUrl [protected]
Definition at line 116 of file CXLRestConsumerComponent.php.
$_behaviorMethods [protected, inherited]
Definition at line 57 of file CXLComponent.php.
$_callbacks = array() [protected]
Definition at line 136 of file CXLRestConsumerComponent.php.
$_debugLevel = false [protected, inherited]
Definition at line 47 of file CXLComponent.php.
$_externalLibraryUrl = '/' [protected]
Definition at line 140 of file CXLRestConsumerComponent.php.
$_httpMethod [protected]
Definition at line 72 of file CXLRestConsumerComponent.php.
$_lastErrorCode [protected]
Definition at line 112 of file CXLRestConsumerComponent.php.
$_lastErrorMessage [protected]
Definition at line 104 of file CXLRestConsumerComponent.php.
$_lastErrorMessageExtra [protected]
Definition at line 108 of file CXLRestConsumerComponent.php.
$_options [protected, inherited]
Reimplemented in CXLConfig.
Definition at line 52 of file CXLComponent.php.
$_payload [protected]
Definition at line 80 of file CXLRestConsumerComponent.php.
$_requestMap [protected]
Definition at line 84 of file CXLRestConsumerComponent.php.
$_requireApiQueryName [protected]
Definition at line 88 of file CXLRestConsumerComponent.php.
$_returnFormat [protected]
Definition at line 76 of file CXLRestConsumerComponent.php.
$_testAltApiKey [protected]
Definition at line 96 of file CXLRestConsumerComponent.php.
$_testApiKey [protected]
Definition at line 92 of file CXLRestConsumerComponent.php.
$_userAgent = 'YiiXL; (+http://github.com/Pogostick/YiiXL)' [protected]
Definition at line 100 of file CXLRestConsumerComponent.php.
$_validateCallbacks = true [protected]
Definition at line 128 of file CXLRestConsumerComponent.php.
$_validateOptions = true [protected]
Definition at line 120 of file CXLRestConsumerComponent.php.
$_validCallbacks = array() [protected]
Definition at line 132 of file CXLRestConsumerComponent.php.
$_validOptions = array() [protected]
Definition at line 124 of file CXLRestConsumerComponent.php.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLRestConsumerComponent'
Our logging tag.
Reimplemented from CXLComponent.
Definition at line 35 of file CXLRestConsumerComponent.php.
The documentation for this class was generated from the following file:
CXLRestConsumerComponent.php