YiiXL -- The Yii Extension Library Of Doom!: CXLBaseHelper Class Reference
CXLBaseHelper Class Reference
The mother of all helper classes.
Public Member Functions
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
getOption ($key, $defaultValue=null, $unsetAfter=false)
Gets a single configuration option.
attachBehavior ($name, $behavior)
Attaches a behavior to this component.
detachBehavior ($name)
Detaches a behavior from the component.
__call ($name, $parameters)
Static Public Member Functions
static initialize ()
Initialize ourselves.
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.helpers.CXLBaseHelper'
Our logging tag.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLComponent'
Our logging tag.
Static Protected Member Functions
static _getCallerObject ($instanceFilter=null)
Walks the backtrace to find the calling object.
Protected Attributes
$_debugLevel = false
$_options
$_behaviorMethods
Detailed Description
The mother of all helper classes.
Definition at line 20 of file CXLBaseHelper.php.
Member Function Documentation
__call ($ name, $ parameters) [inherited]
Parameters:
string $name
array $parameters
Returns:
mixed
Definition at line 190 of file CXLComponent.php.
References YiiXLBase::smartCall().
static _getCallerObject ($ instanceFilter = null) [static, protected, inherited]
Walks the backtrace to find the calling object.
Parameters:
string $instanceFilter Only return objects of this instance
Definition at line 213 of file CXLComponent.php.
References YiiXLBase::o().
attachBehavior ($ name, $ behavior) [inherited]
Attaches a behavior to this component.
Calls the Yii implementation of this method, then injects the behaviors methods into our class.
Parameters:
string $name The behavior's name. It should uniquely identify this behavior.
mixed $behavior the behavior configuration. This is passed as the first parameter to YiiBase::createComponent to create the behavior object.
Returns:
IBehavior the behavior object
Definition at line 147 of file CXLComponent.php.
detachBehavior ($ name) [inherited]
Detaches a behavior from the component.
The behavior's IBehavior::detach method will be invoked.
Parameters:
string $name the behavior's name. It uniquely identifies the behavior.
Returns:
IBehavior the detached behavior. Null if the behavior does not exist.
Since:
1.0.2
Todo:
Implement un-importing methods
Definition at line 176 of file CXLComponent.php.
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 94 of file CXLComponent.php.
Referenced by YiiXLBase::smartCall().
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 67 of file CXLComponent.php.
getOption ($ key, $ defaultValue = null, $ unsetAfter = false) [inherited]
Gets a single configuration option.
Returns:
mixed
Definition at line 132 of file CXLComponent.php.
References YiiXLBase::o().
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 85 of file CXLComponent.php.
static initialize () [static]
Initialize ourselves.
Implements IXLHelper.
Definition at line 38 of file CXLBaseHelper.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 104 of file CXLComponent.php.
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Implements IXLComponent.
Definition at line 76 of file CXLComponent.php.
Field Documentation
$_behaviorMethods [protected, inherited]
Definition at line 57 of file CXLComponent.php.
$_debugLevel = false [protected, inherited]
Definition at line 47 of file CXLComponent.php.
$_options [protected, inherited]
Reimplemented in CXLConfig.
Definition at line 52 of file CXLComponent.php.
const CLASS_LOG_TAG = 'yiixl.core.helpers.CXLBaseHelper'
Our logging tag.
Definition at line 29 of file CXLBaseHelper.php.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLComponent' [inherited]
Our logging tag.
Reimplemented in CXLConfig, CXLConfigFile, CXLApiComponent, CXLRestConsumerComponent, and CXLBaseJobProcess.
Definition at line 38 of file CXLComponent.php.
The documentation for this class was generated from the following file:
CXLBaseHelper.php