YiiXL -- The Yii Extension Library Of Doom!: CXLDataTransformBehavior Class Reference
CXLDataTransformBehavior Class Reference
CXLDataTransformBehavior.
Public Member Functions
getFormat ($eventName= 'afterFind', $formatType= 'date')
Retrieves a format.
setFormat ($eventName= 'afterValidate', $formatType= 'date', $format= 'm/d/Y')
Sets a format.
getDefaultSort ()
Returns the default sort.
setDefaultSort ($sValue)
Sets the default sort.
beforeValidate ($event)
Apply formats before validation.
afterValidate ($event)
Apply any formats.
beforeFind ($event)
Apply any formats.
afterFind ($event)
Apply any formats.
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.behaviors.CXLActiveRecordBehavior'
Our logging tag.
Protected Member Functions
_applyFormat ($column, $value, $eventName= 'view')
Applies the requested format to the value and returns it.
handleEvent ($eventName, CEvent $event)
Process the data and apply formats.
Protected Attributes
$_dateFormat
! Holds the default/configured formats for use when populating fields
$_defaultSort
Default sort.
$_debugLevel = false
User-defined debug flag.
$_options
Our configuration options.
$_behaviorMethods
Imported attached behavior methods.
Detailed Description
CXLDataTransformBehavior.
If attached to a model, fields are transformed per your configuration. Also provides a default sort for a model
Definition at line 23 of file CXLDataTransformBehavior.php.
Member Function Documentation
_applyFormat ($ column, $ value, $ eventName = 'view') [protected]
Applies the requested format to the value and returns it.
Override this method to apply additional format types.
Parameters:
CDbColumnSchema $column
mixed $value
string $eventName
Returns:
mixed
Definition at line 134 of file CXLDataTransformBehavior.php.
References getFormat().
Referenced by handleEvent().
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 92 of file CXLActiveRecordBehavior.php.
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 63 of file CXLActiveRecordBehavior.php.
getDefaultSort ()
Returns the default sort.
Returns:
string
See also:
setDefaultSort
Definition at line 104 of file CXLDataTransformBehavior.php.
getFormat ($ eventName = 'afterFind', $ formatType = 'date')
Retrieves a format.
Parameters:
string $eventName
string $formatType
Returns:
string
Definition at line 76 of file CXLDataTransformBehavior.php.
References YiiXLBase::nvl().
Referenced by _applyFormat().
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 83 of file CXLActiveRecordBehavior.php.
handleEvent ($ eventName, CEvent $ event) [protected]
Process the data and apply formats.
Parameters:
string $eventName
CEvent $event
Definition at line 158 of file CXLDataTransformBehavior.php.
References _applyFormat().
Referenced by afterFind(), afterValidate(), beforeFind(), and beforeValidate().
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 102 of file CXLActiveRecordBehavior.php.
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Returns:
$this
Implements IXLComponent.
Definition at line 73 of file CXLActiveRecordBehavior.php.
setDefaultSort ($ sValue)
Sets the default sort.
Parameters:
string $sValue
Returns:
$this
See also:
getDefaultSort
Definition at line 115 of file CXLDataTransformBehavior.php.
setFormat ($ eventName = 'afterValidate', $ formatType = 'date', $ format = 'm/d/Y')
Sets a format.
Parameters:
string $eventName
string $formatType
string $format
Returns:
$this
Definition at line 89 of file CXLDataTransformBehavior.php.
Field Documentation
array $_behaviorMethods [protected, inherited]
Imported attached behavior methods.
Definition at line 53 of file CXLActiveRecordBehavior.php.
array $_dateFormat [protected]
Initial value:
 array(
    'afterFind' => array(
      'date' => 'm/d/Y',
      'datetime' => 'm/d/Y H:i:s',
    ),
    'afterValidate' => array(
      'date' => 'Y-m-d',
      'datetime' => 'Y-m-d H:i:s',
    ),
  )
! Holds the default/configured formats for use when populating fields
array('eventName' => array(// The event to apply format in 'dataType' => <format> // The format for the display 'method' => <function> // The function to call for formatting), // Send array(object,method) for class methods 'eventName' => array(// The event to apply format in 'dataType' => <format> // The format for the display 'method' => <function> // The function to call for formatting), // Send array(object,method) for class methods ...
Definition at line 45 of file CXLDataTransformBehavior.php.
integer $_debugLevel = false [protected, inherited]
User-defined debug flag.
false = OFF, anything else is up to you.
Definition at line 41 of file CXLActiveRecordBehavior.php.
string $_defaultSort [protected]
Default sort.
See also:
getDefaultSort
setDefaultSort
Definition at line 64 of file CXLDataTransformBehavior.php.
array $_options [protected, inherited]
Our configuration options.
Definition at line 47 of file CXLActiveRecordBehavior.php.
const CLASS_LOG_TAG = 'yiixl.core.behaviors.CXLActiveRecordBehavior' [inherited]
Our logging tag.
Definition at line 31 of file CXLActiveRecordBehavior.php.
The documentation for this class was generated from the following file:
CXLDataTransformBehavior.php