YiiXL -- The Yii Extension Library Of Doom!: CXLSoftDeleteBehavior Class Reference
CXLSoftDeleteBehavior Class Reference
Public Member Functions
getSoftDeleteColumnName ()
Returns the soft-delete column for this model.
setSoftDeleteColumnName ($value)
getSoftDeleteValues ()
Returns the soft-delete values for this model [false,true].
setSoftDeleteValues ($array)
undelete ()
Undeletes a soft-deleted model.
beforeDelete ($event)
Soft deletes models that have that feature CEvent $event.
beforeFind ($event)
Automatically exclude soft-deleted rows.
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.behaviors.CXLActiveRecordBehavior'
Our logging tag.
Protected Attributes
$_softDeleteColumnName = null
$_softDeleteValues
$_debugLevel = false
User-defined debug flag.
$_options
Our configuration options.
$_behaviorMethods
Imported attached behavior methods.
Detailed Description
Definition at line 25 of file CXLSoftDeleteBehavior.php.
Member Function Documentation
beforeDelete ($ event)
Soft deletes models that have that feature CEvent $event.
Returns:
boolean
Exceptions:
CDbException Thrown when we can't update the value
Definition at line 119 of file CXLSoftDeleteBehavior.php.
References YiiXLBase::o().
beforeFind ($ event)
Automatically exclude soft-deleted rows.
Parameters:
CEvent $event
Definition at line 149 of file CXLSoftDeleteBehavior.php.
References YiiXLBase::o().
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 92 of file CXLActiveRecordBehavior.php.
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 63 of file CXLActiveRecordBehavior.php.
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 83 of file CXLActiveRecordBehavior.php.
getSoftDeleteColumnName ()
Returns the soft-delete column for this model.
Returns:
string
Definition at line 53 of file CXLSoftDeleteBehavior.php.
getSoftDeleteValues ()
Returns the soft-delete values for this model [false,true].
Returns:
array
Definition at line 71 of file CXLSoftDeleteBehavior.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 102 of file CXLActiveRecordBehavior.php.
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Returns:
$this
Implements IXLComponent.
Definition at line 73 of file CXLActiveRecordBehavior.php.
setSoftDeleteColumnName ($ value)
Definition at line 62 of file CXLSoftDeleteBehavior.php.
setSoftDeleteValues ($ array)
Definition at line 80 of file CXLSoftDeleteBehavior.php.
undelete ()
Undeletes a soft-deleted model.
Returns:
boolean
Definition at line 93 of file CXLSoftDeleteBehavior.php.
References YiiXLBase::o().
Field Documentation
array $_behaviorMethods [protected, inherited]
Imported attached behavior methods.
Definition at line 53 of file CXLActiveRecordBehavior.php.
integer $_debugLevel = false [protected, inherited]
User-defined debug flag.
false = OFF, anything else is up to you.
Definition at line 41 of file CXLActiveRecordBehavior.php.
array $_options [protected, inherited]
Our configuration options.
Definition at line 47 of file CXLActiveRecordBehavior.php.
$_softDeleteColumnName = null [protected]
Definition at line 35 of file CXLSoftDeleteBehavior.php.
$_softDeleteValues [protected]
Initial value:
 array(
    0,
    1
  )
Definition at line 40 of file CXLSoftDeleteBehavior.php.
const CLASS_LOG_TAG = 'yiixl.core.behaviors.CXLActiveRecordBehavior' [inherited]
Our logging tag.
Definition at line 31 of file CXLActiveRecordBehavior.php.
The documentation for this class was generated from the following file:
CXLSoftDeleteBehavior.php