YiiXL -- The Yii Extension Library Of Doom!: CXLOAuthBehavior Class Reference
CXLOAuthBehavior Class Reference
Public Member Functions
getOAuthToken ()
Retrieves the current OAuth token.
getOAuthObject ()
Retrieves the OAuth object.
getCallbackUrl ()
setCallbackUrl ($callbackUrl)
getIsAuthorized ()
setIsAuthorized ($isAuthorized)
getAccessTokenUrl ()
setAccessTokenUrl ($accessTokenUrl)
getAuthorizeUrl ()
I Appends the current token to the authorizeUrl option.
setAuthorizeUrl ($authorizeUrl)
getRequestTokenUrl ()
setRequestTokenUrl ($requestTokenUrl)
__construct ()
Constructor.
init ()
Initialize this behavior.
storeToken ($token=array())
Stores the current token in a member variable and in the user state oAuthToken.
loadToken ()
Loads a token from the user state oAuthToken.
onUserAuthorized ($event)
User has been authorized event.
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
Data Fields
const CLASS_LOG_TAG = 'yxl.core.behaviors.CXLOAuthBehavior'
Our logging tag.
Protected Attributes
$_oauthToken = null
$_oauthObject = null
$_callbackUrl
$_isAuthorized
$_accessTokenUrl
$_authorizeUrl
$_requestTokenUrl
$_debugLevel = false
User-defined debug flag.
$_options
Our configuration options.
$_behaviorMethods
Imported attached behavior methods.
Detailed Description
Definition at line 26 of file CXLOAuthBehavior.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Definition at line 168 of file CXLOAuthBehavior.php.
Member Function Documentation
getAccessTokenUrl ()
Definition at line 123 of file CXLOAuthBehavior.php.
getAuthorizeUrl ()
I Appends the current token to the authorizeUrl option.
Returns:
string
Definition at line 138 of file CXLOAuthBehavior.php.
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 92 of file CXLBehavior.php.
getCallbackUrl ()
Definition at line 101 of file CXLOAuthBehavior.php.
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 63 of file CXLBehavior.php.
getIsAuthorized ()
Definition at line 112 of file CXLOAuthBehavior.php.
getOAuthObject ()
Retrieves the OAuth object.
Returns:
OAuth
Definition at line 96 of file CXLOAuthBehavior.php.
getOAuthToken ()
Retrieves the current OAuth token.
Returns:
array
Definition at line 87 of file CXLOAuthBehavior.php.
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 83 of file CXLBehavior.php.
getRequestTokenUrl ()
Definition at line 150 of file CXLOAuthBehavior.php.
init ()
Initialize this behavior.
Definition at line 192 of file CXLOAuthBehavior.php.
References loadToken(), onUserAuthorized(), and storeToken().
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
$this
Implements IXLComponent.
Definition at line 102 of file CXLBehavior.php.
loadToken ()
Loads a token from the user state oAuthToken.
Definition at line 260 of file CXLOAuthBehavior.php.
References YiiXLBase::_gs(), and CXLHash::hash().
Referenced by init().
onUserAuthorized ($ event)
User has been authorized event.
Parameters:
CXLOAuthEvent $event
Definition at line 281 of file CXLOAuthBehavior.php.
Referenced by init().
setAccessTokenUrl ($ accessTokenUrl)
Definition at line 128 of file CXLOAuthBehavior.php.
setAuthorizeUrl ($ authorizeUrl)
Definition at line 144 of file CXLOAuthBehavior.php.
setCallbackUrl ($ callbackUrl)
Definition at line 106 of file CXLOAuthBehavior.php.
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Returns:
$this
Implements IXLComponent.
Definition at line 73 of file CXLBehavior.php.
setIsAuthorized ($ isAuthorized)
Definition at line 117 of file CXLOAuthBehavior.php.
setRequestTokenUrl ($ requestTokenUrl)
Definition at line 155 of file CXLOAuthBehavior.php.
storeToken ($ token = array())
Stores the current token in a member variable and in the user state oAuthToken.
Parameters:
array $token
Definition at line 231 of file CXLOAuthBehavior.php.
References YiiXLBase::_ss(), and CXLHash::hash().
Referenced by init().
Field Documentation
$_accessTokenUrl [protected]
Definition at line 67 of file CXLOAuthBehavior.php.
$_authorizeUrl [protected]
Definition at line 72 of file CXLOAuthBehavior.php.
array $_behaviorMethods [protected, inherited]
Imported attached behavior methods.
Definition at line 53 of file CXLBehavior.php.
$_callbackUrl [protected]
Definition at line 57 of file CXLOAuthBehavior.php.
integer $_debugLevel = false [protected, inherited]
User-defined debug flag.
false = OFF, anything else is up to you.
Definition at line 41 of file CXLBehavior.php.
$_isAuthorized [protected]
Definition at line 62 of file CXLOAuthBehavior.php.
$_oauthObject = null [protected]
Definition at line 51 of file CXLOAuthBehavior.php.
$_oauthToken = null [protected]
Definition at line 45 of file CXLOAuthBehavior.php.
array $_options [protected, inherited]
Our configuration options.
Definition at line 47 of file CXLBehavior.php.
$_requestTokenUrl [protected]
Definition at line 77 of file CXLOAuthBehavior.php.
const CLASS_LOG_TAG = 'yxl.core.behaviors.CXLOAuthBehavior'
Our logging tag.
Reimplemented from CXLBehavior.
Definition at line 35 of file CXLOAuthBehavior.php.
The documentation for this class was generated from the following file:
CXLOAuthBehavior.php