YiiXL -- The Yii Extension Library Of Doom!: CXLLog Class Reference
CXLLog Class Reference
A logging helper Utilizes the PHP syslog predefined logging constants.
Public Member Functions
logTrace ($message, $category=null)
Logs a trace message (really a debug).
logEmergency ($message, $category=null)
Logs a message.
logAlert ($message, $category=null)
Logs a message.
logCritical ($message, $category=null)
Logs a message.
logError ($message, $category=null)
Logs a message.
logWarning ($message, $category=null)
Logs a message.
logNotice ($message, $category=null)
Logs a message.
logInfo ($message, $category=null)
Logs a message.
logDebug ($message, $category=null)
Logs a message.
logUser ($message, $category=null)
Logs a message.
logAuth ($message, $category=null)
Logs a message.
logSyslog ($message, $category=null)
Logs a message.
logAuthPriv ($message, $category=null)
Logs a message.
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
getOption ($key, $defaultValue=null, $unsetAfter=false)
Gets a single configuration option.
attachBehavior ($name, $behavior)
Attaches a behavior to this component.
detachBehavior ($name)
Detaches a behavior from the component.
__call ($name, $parameters)
Static Public Member Functions
static initialize ()
Initializer.
static initialize ()
Initialize ourselves.
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.helpers.CXLLog'
Our logging tag.
const CLASS_LOG_TAG = 'yiixl.core.helpers.CXLBaseHelper'
Our logging tag.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLComponent'
Our logging tag.
const LOG_EMERG = 0
Logging Constants.
const LOG_ALERT = 1
const LOG_CRIT = 2
const LOG_ERR = 3
const LOG_WARNING = 4
const LOG_NOTICE = 5
const LOG_INFO = 6
const LOG_DEBUG = 7
const LOG_USER = 8
const LOG_AUTH = 32
const LOG_SYSLOG = 40
const LOG_AUTHPRIV = 80
Protected Member Functions
_log ($message, $level=LOG_INFO, $category=null)
Polymorphic logger.
Static Protected Member Functions
static _getCallerObject ($instanceFilter=null)
Walks the backtrace to find the calling object.
Protected Attributes
$_debugLevel = false
$_options
$_behaviorMethods
Static Protected Attributes
static $_caller
static $_callerLineNumber
static $_validLogLevels
Detailed Description
A logging helper Utilizes the PHP syslog predefined logging constants.
See http://php.net/manual/en/function.syslog.php for more information.
Definition at line 23 of file CXLLog.php.
Member Function Documentation
__call ($ name, $ parameters) [inherited]
Parameters:
string $name
array $parameters
Returns:
mixed
Definition at line 190 of file CXLComponent.php.
References YiiXLBase::smartCall().
static _getCallerObject ($ instanceFilter = null) [static, protected, inherited]
Walks the backtrace to find the calling object.
Parameters:
string $instanceFilter Only return objects of this instance
Definition at line 213 of file CXLComponent.php.
References YiiXLBase::o().
_log ($ message, $ level = LOG_INFO, $ category = null) [protected]
Polymorphic logger.
Parameters:
string $message
int $level
level indicates tje severity of the item being logged. Possible values are:
Levels (in descending order)
Constant
Description
LOG_EMERG
system is unusable
LOG_ALERT
action must be taken immediately
LOG_CRIT
critical conditions
LOG_ERR
error conditions
LOG_WARNING
warning conditions
LOG_NOTICE
normal, but significant, condition
LOG_INFO
informational message
LOG_DEBUG
debug-level message
Parameters:
string $category
Returns:
bool Returns true on success or false on failure.
Definition at line 264 of file CXLLog.php.
Referenced by logAlert(), logAuth(), logAuthPriv(), logCritical(), logDebug(), logEmergency(), logError(), logInfo(), logNotice(), logSyslog(), logTrace(), logUser(), and logWarning().
attachBehavior ($ name, $ behavior) [inherited]
Attaches a behavior to this component.
Calls the Yii implementation of this method, then injects the behaviors methods into our class.
Parameters:
string $name The behavior's name. It should uniquely identify this behavior.
mixed $behavior the behavior configuration. This is passed as the first parameter to YiiBase::createComponent to create the behavior object.
Returns:
IBehavior the behavior object
Definition at line 147 of file CXLComponent.php.
detachBehavior ($ name) [inherited]
Detaches a behavior from the component.
The behavior's IBehavior::detach method will be invoked.
Parameters:
string $name the behavior's name. It uniquely identifies the behavior.
Returns:
IBehavior the detached behavior. Null if the behavior does not exist.
Since:
1.0.2
Todo:
Implement un-importing methods
Definition at line 176 of file CXLComponent.php.
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 94 of file CXLComponent.php.
Referenced by YiiXLBase::smartCall().
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 67 of file CXLComponent.php.
getOption ($ key, $ defaultValue = null, $ unsetAfter = false) [inherited]
Gets a single configuration option.
Returns:
mixed
Definition at line 132 of file CXLComponent.php.
References YiiXLBase::o().
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 85 of file CXLComponent.php.
static initialize () [static, inherited]
Initialize ourselves.
Implements IXLHelper.
Definition at line 38 of file CXLBaseHelper.php.
static initialize () [static]
Initializer.
Definition at line 60 of file CXLLog.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 104 of file CXLComponent.php.
logAlert ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 107 of file CXLLog.php.
References _log().
logAuth ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 187 of file CXLLog.php.
References _log().
logAuthPriv ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 207 of file CXLLog.php.
References _log().
logCritical ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 117 of file CXLLog.php.
References _log().
logDebug ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 167 of file CXLLog.php.
References _log().
logEmergency ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 97 of file CXLLog.php.
References _log().
logError ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 127 of file CXLLog.php.
References _log().
logInfo ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 157 of file CXLLog.php.
References _log().
logNotice ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 147 of file CXLLog.php.
References _log().
logSyslog ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 197 of file CXLLog.php.
References _log().
logTrace ($ message, $ category = null)
Logs a trace message (really a debug).
Parameters:
string $message
string $category
Definition at line 87 of file CXLLog.php.
References _log().
logUser ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 177 of file CXLLog.php.
References _log().
logWarning ($ message, $ category = null)
Logs a message.
Parameters:
string $message
string $category
Definition at line 137 of file CXLLog.php.
References _log().
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Implements IXLComponent.
Definition at line 76 of file CXLComponent.php.
Field Documentation
$_behaviorMethods [protected, inherited]
Definition at line 57 of file CXLComponent.php.
$_caller [static, protected]
Definition at line 41 of file CXLLog.php.
$_callerLineNumber [static, protected]
Definition at line 46 of file CXLLog.php.
$_debugLevel = false [protected, inherited]
Definition at line 47 of file CXLComponent.php.
$_options [protected, inherited]
Reimplemented in CXLConfig.
Definition at line 52 of file CXLComponent.php.
$_validLogLevels [static, protected]
Definition at line 51 of file CXLLog.php.
const CLASS_LOG_TAG = 'yiixl.core.helpers.CXLLog'
Our logging tag.
Definition at line 32 of file CXLLog.php.
const CLASS_LOG_TAG = 'yiixl.core.helpers.CXLBaseHelper' [inherited]
Our logging tag.
Definition at line 29 of file CXLBaseHelper.php.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLComponent' [inherited]
Our logging tag.
Reimplemented in CXLConfig, CXLConfigFile, CXLApiComponent, CXLRestConsumerComponent, and CXLBaseJobProcess.
Definition at line 38 of file CXLComponent.php.
const LOG_ALERT = 1 [inherited]
Definition at line 100 of file interfaces.php.
const LOG_AUTH = 32 [inherited]
Definition at line 108 of file interfaces.php.
const LOG_AUTHPRIV = 80 [inherited]
Definition at line 110 of file interfaces.php.
const LOG_CRIT = 2 [inherited]
Definition at line 101 of file interfaces.php.
const LOG_DEBUG = 7 [inherited]
Definition at line 106 of file interfaces.php.
const LOG_EMERG = 0 [inherited]
Logging Constants.
Definition at line 99 of file interfaces.php.
const LOG_ERR = 3 [inherited]
Definition at line 102 of file interfaces.php.
const LOG_INFO = 6 [inherited]
Definition at line 105 of file interfaces.php.
const LOG_NOTICE = 5 [inherited]
Definition at line 104 of file interfaces.php.
const LOG_SYSLOG = 40 [inherited]
Definition at line 109 of file interfaces.php.
const LOG_USER = 8 [inherited]
Definition at line 107 of file interfaces.php.
const LOG_WARNING = 4 [inherited]
Definition at line 103 of file interfaces.php.
The documentation for this class was generated from the following file:
CXLLog.php