YiiXL -- The Yii Extension Library Of Doom!: CXLWidget Class Reference
CXLWidget Class Reference
CXLWidget Pretty much identical to CXLComponent but offers a little bit of extra functionality.
Public Member Functions
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
getCssQueue ()
Returns the css file queue.
setCssQueue ($value)
Sets the css file queue.
getOption ($key, $defaultValue=null, $unsetAfter=false)
Gets a single configuration option.
__construct ($owner=null, $options=array())
Constructor.
init ()
Initialize this widget.
run ()
Executes the widget.
pushCssFile ($path, $media= 'screen')
Pushes a css file onto the page load stack.
popCssFile ()
Pops a css file off the top of the page load stack.
pushScriptFile ($path, $position=CClientScript::POS_HEAD)
Pushes a script onto the page load stack.
popScriptFile ()
Pops a script file off the top of the page load stack.
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.ui.CXLWidget'
Our logging tag.
Protected Member Functions
_render ()
Renders the widget queues in the right order/sequence.
_renderContainer ($endTag=null)
Renders either an open or close container tag for this widget.
_renderCss ()
Renders any CSS code for the widget.
_renderHtml ()
Renders any HTML for the widget.
_renderScripts ()
Renders any CSS code for the widget.
_loadConfiguration ($options=array(), $overwriteExisting=true)
Loads an array into properties if they exist.
Protected Attributes
$_debugLevel = false
$_options
$_behaviorMethods
$_cssQueue = array()
$_scriptQueue = array()
Detailed Description
CXLWidget Pretty much identical to CXLComponent but offers a little bit of extra functionality.
Forced to not be a descendent of {
See also:
CIXComponent} because of the depth of the {
CInputWidget} heirarchy. Thus this object duplicates {
CXLComponent}.
Definition at line 23 of file CXLWidget.php.
Constructor & Destructor Documentation
__construct ($ owner = null, $ options = array())
Constructor.
Parameters:
CBaseController $owner The owner/creator of this widget. Either a widget or a controller.
array $options Additional options to pass on to the widget
Definition at line 149 of file CXLWidget.php.
References _loadConfiguration().
Member Function Documentation
_loadConfiguration ($ options = array(), $ overwriteExisting = true) [protected]
Loads an array into properties if they exist.
Parameters:
array $options
Definition at line 331 of file CXLWidget.php.
Referenced by __construct().
_render () [protected]
Renders the widget queues in the right order/sequence.
Definition at line 249 of file CXLWidget.php.
References _renderContainer(), _renderCss(), _renderHtml(), and _renderScripts().
Referenced by run().
_renderContainer ($ endTag = null) [protected]
Renders either an open or close container tag for this widget.
Parameters:
string $endTag
Returns:
string The name of the tag used to open the container
Definition at line 265 of file CXLWidget.php.
References getOption().
Referenced by _render().
_renderCss () [protected]
Renders any CSS code for the widget.
We don't technically render here we merely post up to the master Yii arbitrator
Returns:
boolean
Definition at line 290 of file CXLWidget.php.
References YiiXLBase::_gbu(), and YiiXLBase::_rcf().
Referenced by _render().
_renderHtml () [protected]
Renders any HTML for the widget.
Returns:
boolean
Definition at line 305 of file CXLWidget.php.
Referenced by _render().
_renderScripts () [protected]
Renders any CSS code for the widget.
We don't technically render here we merely post up to the master Yii arbitrator
Returns:
boolean
Definition at line 316 of file CXLWidget.php.
References YiiXLBase::_gbu(), and YiiXLBase::_rsf().
Referenced by _render().
getBehaviorMethods ()
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 96 of file CXLWidget.php.
getCssQueue ()
Returns the css file queue.
Returns:
array
Definition at line 116 of file CXLWidget.php.
getDebugLevel ()
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 68 of file CXLWidget.php.
getOption ($ key, $ defaultValue = null, $ unsetAfter = false)
Gets a single configuration option.
Returns:
mixed
Definition at line 135 of file CXLWidget.php.
References YiiXLBase::o().
Referenced by _renderContainer().
getOptions ()
Gets configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 87 of file CXLWidget.php.
init ()
Initialize this widget.
Definition at line 160 of file CXLWidget.php.
References YiiXLBase::o(), pushCssFile(), and pushScriptFile().
loadOptions ($ options = array())
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 106 of file CXLWidget.php.
popCssFile ()
Pops a css file off the top of the page load stack.
Returns:
string|null
Definition at line 209 of file CXLWidget.php.
popScriptFile ()
Pops a script file off the top of the page load stack.
Returns:
string|null
Definition at line 237 of file CXLWidget.php.
pushCssFile ($ path, $ media = 'screen')
Pushes a css file onto the page load stack.
Parameters:
string $path Path of css relative to doc_root
string $id
Definition at line 195 of file CXLWidget.php.
Referenced by init().
pushScriptFile ($ path, $ position = CClientScript::POS_HEAD)
Pushes a script onto the page load stack.
Parameters:
string $path Path of script relative to doc_root
integer $position
string $id
Definition at line 221 of file CXLWidget.php.
Referenced by init().
run ()
Executes the widget.
This method is called by CBaseController::endWidget.
Definition at line 177 of file CXLWidget.php.
References _render().
setCssQueue ($ value)
Sets the css file queue.
Returns:
array
Definition at line 125 of file CXLWidget.php.
setDebugLevel ($ value = false)
Sets the debug level.
Parameters:
integer The new debug level
Implements IXLComponent.
Definition at line 77 of file CXLWidget.php.
Field Documentation
$_behaviorMethods [protected]
Definition at line 50 of file CXLWidget.php.
$_cssQueue = array() [protected]
Definition at line 54 of file CXLWidget.php.
$_debugLevel = false [protected]
Definition at line 42 of file CXLWidget.php.
$_options [protected]
Definition at line 46 of file CXLWidget.php.
$_scriptQueue = array() [protected]
Definition at line 58 of file CXLWidget.php.
const CLASS_LOG_TAG = 'yiixl.core.ui.CXLWidget'
Our logging tag.
Definition at line 33 of file CXLWidget.php.
The documentation for this class was generated from the following file:
CXLWidget.php