YiiXL -- The Yii Extension Library Of Doom!: CXLHash Class Reference
CXLHash Class Reference
Hash code/password helpers.
Public Member Functions
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
getOption ($key, $defaultValue=null, $unsetAfter=false)
Gets a single configuration option.
attachBehavior ($name, $behavior)
Attaches a behavior to this component.
detachBehavior ($name)
Detaches a behavior from the component.
__call ($name, $parameters)
Static Public Member Functions
static generate ($hashLength=20, $hashType=self::ALL)
Generates a unique hash code.
static hash ($hashTarget=null, $hashType=self::SHA1, $hashLength=32, $rawOutput=false)
Generic hashing method.
static initialize ()
Initialize ourselves.
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.components.CXLHash'
Our logging tag.
const ALL = 0
Our hash types.
const ALPHA_LOWER = 1
const ALPHA_UPPER = 2
const ALPHA = 3
const ALPHA_NUMERIC = 4
const ALPHA_LOWER_NUMERIC = 5
const NUMERIC = 6
const ALPHA_LOWER_NUMERIC_IDIOTPROOF = 7
const MD5 = 1
Hashing methods.
const SHA1 = 2
const CRC32 = 18
const CLASS_LOG_TAG = 'yiixl.core.helpers.CXLBaseHelper'
Our logging tag.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLComponent'
Our logging tag.
const ACCESS_TO_NONE = -1
const ACCESS_TO_ANY = 0
const ACCESS_TO_GUEST = 1
const ACCESS_TO_AUTH = 2
const ACCESS_TO_ADMIN = 3
const ACCESS_TO_ADMIN_LEVEL_0 = 3
const ACCESS_TO_ADMIN_LEVEL_1 = 4
const ACCESS_TO_ADMIN_LEVEL_2 = 5
Static Protected Member Functions
static _getCallerObject ($instanceFilter=null)
Walks the backtrace to find the calling object.
Protected Attributes
$_debugLevel = false
$_options
$_behaviorMethods
Static Protected Attributes
static $_hashSeeds
Detailed Description
Hash code/password helpers.
Definition at line 20 of file CXLHash.php.
Member Function Documentation
__call ($ name, $ parameters) [inherited]
Parameters:
string $name
array $parameters
Returns:
mixed
Definition at line 190 of file CXLComponent.php.
References YiiXLBase::smartCall().
static _getCallerObject ($ instanceFilter = null) [static, protected, inherited]
Walks the backtrace to find the calling object.
Parameters:
string $instanceFilter Only return objects of this instance
Definition at line 213 of file CXLComponent.php.
References YiiXLBase::o().
attachBehavior ($ name, $ behavior) [inherited]
Attaches a behavior to this component.
Calls the Yii implementation of this method, then injects the behaviors methods into our class.
Parameters:
string $name The behavior's name. It should uniquely identify this behavior.
mixed $behavior the behavior configuration. This is passed as the first parameter to YiiBase::createComponent to create the behavior object.
Returns:
IBehavior the behavior object
Definition at line 147 of file CXLComponent.php.
detachBehavior ($ name) [inherited]
Detaches a behavior from the component.
The behavior's IBehavior::detach method will be invoked.
Parameters:
string $name the behavior's name. It uniquely identifies the behavior.
Returns:
IBehavior the detached behavior. Null if the behavior does not exist.
Since:
1.0.2
Todo:
Implement un-importing methods
Definition at line 176 of file CXLComponent.php.
static generate ($ hashLength = 20, $ hashType = self::ALL) [static]
Generates a unique hash code.
Parameters:
int $hashLength
Returns:
string
Definition at line 87 of file CXLHash.php.
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 94 of file CXLComponent.php.
Referenced by YiiXLBase::smartCall().
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 67 of file CXLComponent.php.
getOption ($ key, $ defaultValue = null, $ unsetAfter = false) [inherited]
Gets a single configuration option.
Returns:
mixed
Definition at line 132 of file CXLComponent.php.
References YiiXLBase::o().
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 85 of file CXLComponent.php.
static hash ($ hashTarget = null, $ hashType = self::SHA1, $ hashLength = 32, $ rawOutput = false) [static]
Generic hashing method.
Will hash any string or generate a random hash and hash that!
Parameters:
string $hashTarget The value to hash..
integer $hashType [optional] The type of hash to create. Can be {
See also:
CXLHash::MD5}, {
CXLHash::SHA1}, or CXLHash#CRC32. Defaults to {
CXLHash::SHA1}.
Parameters:
integer $hashLength [optional] The length of the hash to return. Only applies if $hashType is not MD5, SH1, or CRC32. . Defaults to 32.
boolean $rawOutput [optional] If $rawOutput is true, then the hash digest is returned in raw binary format instead of ASCII.
Returns:
string
Definition at line 109 of file CXLHash.php.
Referenced by YiiXLBase::createUniqueName(), CXLOAuthBehavior::loadToken(), and CXLOAuthBehavior::storeToken().
static initialize () [static, inherited]
Initialize ourselves.
Implements IXLHelper.
Definition at line 38 of file CXLBaseHelper.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 104 of file CXLComponent.php.
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Implements IXLComponent.
Definition at line 76 of file CXLComponent.php.
Field Documentation
$_behaviorMethods [protected, inherited]
Definition at line 57 of file CXLComponent.php.
$_debugLevel = false [protected, inherited]
Definition at line 47 of file CXLComponent.php.
$_hashSeeds [static, protected]
Initial value:
 array(
    self::ALL => array( 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' ),
    self::ALPHA_LOWER => array( 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z' ),
    self::ALPHA_UPPER => array( 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z' ),
    self::ALPHA => array( 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z' ),
    self::ALPHA_NUMERIC => array( 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' ),
    self::ALPHA_LOWER_NUMERIC => array( 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' ),
    self::NUMERIC => array( '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' ),
    self::ALPHA_LOWER_NUMERIC_IDIOTPROOF => array( 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'j', 'k', 'm', 'n', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '2', '3', '4', '5', '6', '7', '8', '9' ),
  )
Definition at line 66 of file CXLHash.php.
$_options [protected, inherited]
Reimplemented in CXLConfig.
Definition at line 52 of file CXLComponent.php.
const ALL = 0
Our hash types.
Definition at line 39 of file CXLHash.php.
const ALPHA = 3
Definition at line 42 of file CXLHash.php.
const ALPHA_LOWER = 1
Definition at line 40 of file CXLHash.php.
const ALPHA_LOWER_NUMERIC = 5
Definition at line 44 of file CXLHash.php.
const ALPHA_LOWER_NUMERIC_IDIOTPROOF = 7
Definition at line 46 of file CXLHash.php.
const ALPHA_NUMERIC = 4
Definition at line 43 of file CXLHash.php.
const ALPHA_UPPER = 2
Definition at line 41 of file CXLHash.php.
const CLASS_LOG_TAG = 'yiixl.core.helpers.CXLBaseHelper' [inherited]
Our logging tag.
Definition at line 29 of file CXLBaseHelper.php.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLHash'
Our logging tag.
Definition at line 29 of file CXLHash.php.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLComponent' [inherited]
Our logging tag.
Reimplemented in CXLConfig, CXLConfigFile, CXLApiComponent, CXLRestConsumerComponent, and CXLBaseJobProcess.
Definition at line 38 of file CXLComponent.php.
const CRC32 = 18
Definition at line 55 of file CXLHash.php.
const MD5 = 1
Hashing methods.
Definition at line 53 of file CXLHash.php.
const NUMERIC = 6
Definition at line 45 of file CXLHash.php.
const SHA1 = 2
Definition at line 54 of file CXLHash.php.
The documentation for this class was generated from the following file:
CXLHash.php