YiiXL -- The Yii Extension Library Of Doom!: CXLConfigFile Class Reference
CXLConfigFile Class Reference
CXLConfigFile implements the CXLConfig class that stored in a file.
Public Member Functions
load ($path=null)
save ($path=null)
getOption ($key, $defaultValue=null)
Retrieve a value from the options collection.
getOption ($key, $defaultValue=null, $unsetAfter=false)
Gets a single configuration option.
toArray ()
Return an associative array of all settings.
merge (CXLConfig $mergeConfig)
Merge another CXLConfig with this one.
jsonEncode ($jsonOptions=null)
Returns the JSON representation of a value http://php.net/manual/en/function.json-encode.php.
jsonDecode ($json, $assoc=null, $depth=null)
Decodes a JSON string http://php.net/manual/en/function.json-decode.php.
count ()
Required by Countable interface.
current ()
Required by Iterator interface.
key ()
Required by Iterator interface.
next ()
Required by Iterator interface.
rewind ()
Required by Iterator interface.
valid ()
Required by Iterator interface.
__get ($key)
Check our options before we pass the buck.
__set ($key, $value)
Only allow setting of a property if not read-only.
__clone ()
Deep copy of this collection.
__isset ($key)
__unset ($key)
setReadOnly ($value=true)
Set the read-only flag.
getReadOnly ()
Gets the read-only flag.
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
getBehaviorMethods ()
Gets the list of registered behavior methods.
loadOptions ($options=array())
Loads the configuration options.
attachBehavior ($name, $behavior)
Attaches a behavior to this component.
detachBehavior ($name)
Detaches a behavior from the component.
__call ($name, $parameters)
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.components.config.CXLConfigFile'
Our logging tag.
const ASSOC_ARRAY = 0
The output formats available.
const JSON = 1
const XML = 2
const INI = 3
Static Protected Member Functions
static _getCallerObject ($instanceFilter=null)
Walks the backtrace to find the calling object.
Protected Attributes
$_configFileFormat = self::ASSOC_ARRAY
$_configFileName = 'config.php'
$_configFilePath = 'application.config'
$_readOnly = true
$_iterationIndex = 0
$_optionCount
$_options
$_skipNext
$_lastError = null
$_debugLevel = false
$_behaviorMethods
Detailed Description
CXLConfigFile implements the CXLConfig class that stored in a file.
Definition at line 20 of file CXLConfigFile.php.
Member Function Documentation
__call ($ name, $ parameters) [inherited]
Parameters:
string $name
array $parameters
Returns:
mixed
Definition at line 190 of file CXLComponent.php.
References YiiXLBase::smartCall().
__clone () [inherited]
Deep copy of this collection.
Returns:
void
Definition at line 329 of file CXLConfig.php.
References CXLConfig::$_options.
__get ($ key) [inherited]
Check our options before we pass the buck.
Parameters:
string $key
Returns:
mixed
Definition at line 281 of file CXLConfig.php.
References CXLConfig::getOption().
__isset ($ key) [inherited]
Parameters:
string $key
Returns:
boolean
Definition at line 348 of file CXLConfig.php.
__set ($ key, $ value) [inherited]
Only allow setting of a property if not read-only.
Parameters:
string $key
mixed $value
Exceptions:
CXLReadOnlyException
Returns:
CXLConfig
Definition at line 296 of file CXLConfig.php.
References CXLConfig::count().
__unset ($ key) [inherited]
Parameters:
string $key
Exceptions:
CXLReadOnlyException
Returns:
CXLConfig
Definition at line 361 of file CXLConfig.php.
References CXLConfig::count(), and YiiXLBase::uo().
static _getCallerObject ($ instanceFilter = null) [static, protected, inherited]
Walks the backtrace to find the calling object.
Parameters:
string $instanceFilter Only return objects of this instance
Definition at line 213 of file CXLComponent.php.
References YiiXLBase::o().
attachBehavior ($ name, $ behavior) [inherited]
Attaches a behavior to this component.
Calls the Yii implementation of this method, then injects the behaviors methods into our class.
Parameters:
string $name The behavior's name. It should uniquely identify this behavior.
mixed $behavior the behavior configuration. This is passed as the first parameter to YiiBase::createComponent to create the behavior object.
Returns:
IBehavior the behavior object
Definition at line 147 of file CXLComponent.php.
count () [inherited]
Required by Countable interface.
Returns:
int
Definition at line 213 of file CXLConfig.php.
Referenced by CXLConfig::__construct(), CXLConfig::__set(), and CXLConfig::__unset().
current () [inherited]
Required by Iterator interface.
Returns:
mixed
Definition at line 222 of file CXLConfig.php.
detachBehavior ($ name) [inherited]
Detaches a behavior from the component.
The behavior's IBehavior::detach method will be invoked.
Parameters:
string $name the behavior's name. It uniquely identifies the behavior.
Returns:
IBehavior the detached behavior. Null if the behavior does not exist.
Since:
1.0.2
Todo:
Implement un-importing methods
Definition at line 176 of file CXLComponent.php.
getBehaviorMethods () [inherited]
Gets the list of registered behavior methods.
Returns:
array
Implements IXLComponent.
Definition at line 94 of file CXLComponent.php.
Referenced by YiiXLBase::smartCall().
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implements IXLComponent.
Definition at line 67 of file CXLComponent.php.
getOption ($ key, $ defaultValue = null, $ unsetAfter = false) [inherited]
Gets a single configuration option.
Returns:
mixed
Definition at line 132 of file CXLComponent.php.
References YiiXLBase::o().
getOption ($ key, $ defaultValue = null) [inherited]
Retrieve a value from the options collection.
Parameters:
string $key
mixed $defaultValue
Returns:
mixed
Definition at line 103 of file CXLConfig.php.
References YiiXLBase::o().
Referenced by CXLConfig::__get().
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implements IXLComponent.
Definition at line 85 of file CXLComponent.php.
getReadOnly () [inherited]
Gets the read-only flag.
Returns:
boolean
Definition at line 410 of file CXLConfig.php.
jsonDecode ($ json, $ assoc = null, $ depth = null) [inherited]
Decodes a JSON string http://php.net/manual/en/function.json-decode.php.
Parameters:
string $json
The json string being decoded.
Parameters:
bool $assoc [optional]
When true, returned objects will be converted into associative arrays.
Parameters:
int $depth [optional]
User specified recursion depth.
Returns:
mixed the value encoded in json in appropriate PHP type. Values true, false and null (case-insensitive) are returned as true, false and respectively. is returned if the json cannot be decoded or if the encoded data is deeper than the recursion limit.
Definition at line 200 of file CXLConfig.php.
jsonEncode ($ jsonOptions = null) [inherited]
Returns the JSON representation of a value http://php.net/manual/en/function.json-encode.php.
Parameters:
mixed $value
The value being encoded. Can be any type except a resource.
This function only works with UTF-8 encoded data.
Parameters:
int $options [optional]
Bitmask consisting of JSON_HEX_QUOT, JSON_HEX_TAG, JSON_HEX_AMP, JSON_HEX_APOS, JSON_FORCE_OBJECT.
Returns:
string a JSON encoded string on success.
Definition at line 175 of file CXLConfig.php.
References CXLConfig::toArray().
key () [inherited]
Required by Iterator interface.
Returns:
mixed
Definition at line 232 of file CXLConfig.php.
load ($ path = null)
Parameters:
string $path
Returns:
bool
Definition at line 71 of file CXLConfigFile.php.
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array
Returns:
CXLComponent
Implements IXLComponent.
Definition at line 104 of file CXLComponent.php.
merge (CXLConfig $ mergeConfig) [inherited]
Merge another CXLConfig with this one.
The items in $mergeOptions will override the same named items in the current collection.
Parameters:
CXLConfig $mergeConfig
Returns:
CXLConfig
Definition at line 133 of file CXLConfig.php.
next () [inherited]
Required by Iterator interface.
Definition at line 240 of file CXLConfig.php.
rewind () [inherited]
Required by Iterator interface.
Definition at line 256 of file CXLConfig.php.
save ($ path = null)
Parameters:
string $path
Returns:
bool
Definition at line 80 of file CXLConfigFile.php.
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Implements IXLComponent.
Definition at line 76 of file CXLComponent.php.
setReadOnly ($ value = true) [inherited]
Set the read-only flag.
Returns:
CXLConfig
Definition at line 393 of file CXLConfig.php.
toArray () [inherited]
Return an associative array of all settings.
Returns:
array
Definition at line 112 of file CXLConfig.php.
References CXLConfig::$_options.
Referenced by CXLConfig::jsonEncode().
valid () [inherited]
Required by Iterator interface.
Returns:
boolean
Definition at line 267 of file CXLConfig.php.
Field Documentation
$_behaviorMethods [protected, inherited]
Definition at line 57 of file CXLComponent.php.
$_configFileFormat = self::ASSOC_ARRAY [protected]
Definition at line 49 of file CXLConfigFile.php.
$_configFileName = 'config.php' [protected]
Definition at line 55 of file CXLConfigFile.php.
$_configFilePath = 'application.config' [protected]
Definition at line 61 of file CXLConfigFile.php.
$_debugLevel = false [protected, inherited]
Definition at line 47 of file CXLComponent.php.
$_iterationIndex = 0 [protected, inherited]
Definition at line 47 of file CXLConfig.php.
$_lastError = null [protected, inherited]
Definition at line 69 of file CXLConfig.php.
$_optionCount [protected, inherited]
Definition at line 52 of file CXLConfig.php.
$_options [protected, inherited]
Reimplemented from CXLComponent.
Definition at line 57 of file CXLConfig.php.
Referenced by CXLConfig::__clone(), and CXLConfig::toArray().
$_readOnly = true [protected, inherited]
Definition at line 42 of file CXLConfig.php.
$_skipNext [protected, inherited]
Definition at line 64 of file CXLConfig.php.
const ASSOC_ARRAY = 0
The output formats available.
Definition at line 36 of file CXLConfigFile.php.
const CLASS_LOG_TAG = 'yiixl.core.components.config.CXLConfigFile'
Our logging tag.
Reimplemented from CXLConfig.
Definition at line 30 of file CXLConfigFile.php.
const INI = 3
Definition at line 39 of file CXLConfigFile.php.
const JSON = 1
Definition at line 37 of file CXLConfigFile.php.
const XML = 2
Definition at line 38 of file CXLConfigFile.php.
The documentation for this class was generated from the following file:
CXLConfigFile.php