YiiXL -- The Yii Extension Library Of Doom!: CXLWebModule Class Reference
CXLWebModule Class Reference
CXLWebModule provides extra functionality to the base module functionality of Yii.
Public Member Functions
getConfigPath ()
setConfigPath ($sValue)
getAssetPath ()
setAssetPath ($sValue)
getAssetUrl ()
init ()
Initialize.
getDebugLevel ()
Gets the debug level.
setDebugLevel ($value=false)
Sets the debug level.
getOptions ()
Gets the configuration options.
loadOptions ($options=array())
Loads the configuration options.
getBehaviorMethods ()
Gets behavior methods.
Data Fields
const CLASS_LOG_TAG = 'yiixl.core.components.CXLWebModule'
Our logging tag.
Protected Member Functions
setAssetUrl ($sUrl)
_setAssetPaths ()
Initializes the asset manager for this module.
Protected Attributes
$_configPath = null
$_assetPath = null
$_assetUrl = null
Detailed Description
CXLWebModule provides extra functionality to the base module functionality of Yii.
Definition at line 20 of file CXLWebModule.php.
Member Function Documentation
_setAssetPaths () [protected]
Initializes the asset manager for this module.
Definition at line 82 of file CXLWebModule.php.
References YiiXLBase::_a().
Referenced by init().
getAssetPath ()
Definition at line 40 of file CXLWebModule.php.
getAssetUrl ()
Definition at line 44 of file CXLWebModule.php.
getBehaviorMethods () [inherited]
Gets behavior methods.
Needed to implement lightweight helper classes
Returns:
array
Implemented in CXLActiveRecordBehavior, CXLBehavior, CXLComponent, and CXLWidget.
getConfigPath ()
Definition at line 36 of file CXLWebModule.php.
getDebugLevel () [inherited]
Gets the debug level.
Returns:
integer
Implemented in CXLActiveRecordBehavior, CXLBehavior, CXLComponent, CXLLiveLogRoute, and CXLWidget.
getOptions () [inherited]
Gets the configuration options.
Returns:
array
Implemented in CXLActiveRecordBehavior, CXLBehavior, CXLComponent, CXLLiveLogRoute, and CXLWidget.
Referenced by CXLOptions::loadConfiguration().
init ()
Initialize.
Definition at line 55 of file CXLWebModule.php.
References _setAssetPaths().
loadOptions ($ options = array()) [inherited]
Loads the configuration options.
Parameters:
array $options
Returns:
CXLComponent
Implemented in CXLActiveRecordBehavior, CXLBehavior, CXLComponent, and CXLWidget.
Referenced by CXLOptions::loadConfiguration().
setAssetPath ($ sValue)
Definition at line 41 of file CXLWebModule.php.
setAssetUrl ($ sUrl) [protected]
Definition at line 45 of file CXLWebModule.php.
setConfigPath ($ sValue)
Definition at line 37 of file CXLWebModule.php.
setDebugLevel ($ value = false) [inherited]
Sets the debug level.
Parameters:
integer The new debug level
Implemented in CXLActiveRecordBehavior, CXLBehavior, CXLComponent, CXLLiveLogRoute, and CXLWidget.
Field Documentation
$_assetPath = null [protected]
Definition at line 39 of file CXLWebModule.php.
$_assetUrl = null [protected]
Definition at line 43 of file CXLWebModule.php.
$_configPath = null [protected]
Definition at line 35 of file CXLWebModule.php.
const CLASS_LOG_TAG = 'yiixl.core.components.CXLWebModule'
Our logging tag.
Definition at line 29 of file CXLWebModule.php.
The documentation for this class was generated from the following file:
CXLWebModule.php