YiiXL -- The Yii Extension Library Of Doom!: CXLController Properties
CXLController Properties
[Properties]
These are the properties accessors for the CXLController.
Functions
getIsPostRequest ()
Convenience access to isPostRequest.
getIsAjaxRequest ()
Convenience access to isAjaxRequest.
getAppBaseUrl ()
Returns the base url of the current app.
getMenu ()
setMenu ($value)
getBreadcrumbs ()
setBreadcrumbs ($value)
getPageHeading ()
setPageHeading ($value)
getActionMethodPrefix ()
setActionMethodPrefix ($value)
getCurrentModel ()
setCurrentModel ($value)
getModelClass ()
setModelClass ($value)
getContentTemplate ()
setContentTemplate ($value)
getAutoFindLayout ()
setAutoFindLayout ($value)
getAutoFindAction ()
setAutoFindAction ($value)
getAdminCommandMap ()
setAdminCommandMap ($value)
addCommandToMap ($key, $value=null, $property=null)
getPortletActions ()
setPortletActions ($value)
addPortletAction ($sName, $arCallback)
getViewData ()
setViewData ($value)
getExtraViewDataList ()
setExtraViewDataList ($value)
getExtraViewDataPrefix ()
setExtraViewDataPrefix ($value)
Detailed Description
These are the properties accessors for the CXLController.
Function Documentation
addCommandToMap ($ key, $ value = null, $ property = null) [inherited]
Parameters:
string $key
mixed $value
string $property
Returns:
CXLController
Definition at line 841 of file CXLController.php.
addPortletAction ($ sName, $ arCallback) [inherited]
Parameters:
$sName
$arCallback
Returns:
CXLController
Definition at line 874 of file CXLController.php.
getActionMethodPrefix () [inherited]
Returns:
string
Definition at line 712 of file CXLController.php.
getAdminCommandMap () [inherited]
Returns:
array
Definition at line 820 of file CXLController.php.
getAppBaseUrl () [inherited]
Returns the base url of the current app.
Returns:
string
Definition at line 650 of file CXLController.php.
References YiiXLBase::_gbu().
getAutoFindAction () [inherited]
Returns:
bool
Definition at line 802 of file CXLController.php.
getAutoFindLayout () [inherited]
Returns:
bool
Definition at line 784 of file CXLController.php.
getBreadcrumbs () [inherited]
Returns:
array
Definition at line 676 of file CXLController.php.
getContentTemplate () [inherited]
Returns:
null|string
Definition at line 766 of file CXLController.php.
getCurrentModel () [inherited]
Returns:
CActiveRecord|null
Definition at line 730 of file CXLController.php.
getExtraViewDataList () [protected, inherited]
Returns:
array
Definition at line 901 of file CXLController.php.
getExtraViewDataPrefix () [protected, inherited]
Returns:
string
Definition at line 919 of file CXLController.php.
getIsAjaxRequest () [inherited]
Convenience access to isAjaxRequest.
Returns:
boolean
Definition at line 641 of file CXLController.php.
References YiiXLBase::isAjaxRequest().
getIsPostRequest () [inherited]
Convenience access to isPostRequest.
Returns:
boolean
Definition at line 632 of file CXLController.php.
References YiiXLBase::isPostRequest().
Referenced by CXLController::_processCommand().
getMenu () [inherited]
Returns:
array
Definition at line 658 of file CXLController.php.
getModelClass () [inherited]
Returns:
null|string
Definition at line 748 of file CXLController.php.
getPageHeading () [inherited]
Returns:
Definition at line 694 of file CXLController.php.
getPortletActions () [inherited]
Returns:
array
Definition at line 854 of file CXLController.php.
getViewData () [protected, inherited]
Returns:
array
Definition at line 883 of file CXLController.php.
setActionMethodPrefix ($ value) [inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 721 of file CXLController.php.
setAdminCommandMap ($ value) [inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 829 of file CXLController.php.
setAutoFindAction ($ value) [inherited]
Parameters:
$value
Returns:
$this
Definition at line 811 of file CXLController.php.
setAutoFindLayout ($ value) [inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 793 of file CXLController.php.
setBreadcrumbs ($ value) [inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 685 of file CXLController.php.
setContentTemplate ($ value) [inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 775 of file CXLController.php.
setCurrentModel ($ value) [protected, inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 739 of file CXLController.php.
setExtraViewDataList ($ value) [protected, inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 910 of file CXLController.php.
setExtraViewDataPrefix ($ value) [protected, inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 928 of file CXLController.php.
setMenu ($ value) [inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 667 of file CXLController.php.
setModelClass ($ value) [protected, inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 757 of file CXLController.php.
Referenced by CXLController::loadCurrentModel().
setPageHeading ($ value) [inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 703 of file CXLController.php.
setPortletActions ($ value) [inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 863 of file CXLController.php.
setViewData ($ value) [protected, inherited]
Parameters:
$value
Returns:
CXLController
Definition at line 892 of file CXLController.php.