YiiXL -- The Yii Extension Library Of Doom!: Behavior Events
Behavior Events
[Events]
These events are handled or triggered by behaviors.
Functions
beforeValidate ($event)
Apply formats before validation.
afterValidate ($event)
Apply any formats.
beforeFind ($event)
Apply any formats.
afterFind ($event)
Apply any formats.
Detailed Description
These events are handled or triggered by behaviors.
Function Documentation
afterFind ($ event) [inherited]
Apply any formats.
Parameters:
CEvent $event
Definition at line 265 of file CXLDataTransformBehavior.php.
References CXLDataTransformBehavior::handleEvent().
afterValidate ($ event) [inherited]
Apply any formats.
Parameters:
CEvent $event
Returns:
mixed
Definition at line 227 of file CXLDataTransformBehavior.php.
References CXLDataTransformBehavior::handleEvent().
beforeFind ($ event) [inherited]
Apply any formats.
Parameters:
CEvent $event
Returns:
mixed
Definition at line 237 of file CXLDataTransformBehavior.php.
References CXLDataTransformBehavior::handleEvent().
beforeValidate ($ event) [inherited]
Apply formats before validation.
Parameters:
CModelEvent $event parameter
Returns:
mixed
Definition at line 217 of file CXLDataTransformBehavior.php.
References CXLDataTransformBehavior::handleEvent().