YiiXL -- The Yii Extension Library Of Doom!: Events
Events
Functions
beforeValidate ($event)
afterValidate ($event)
afterFind ($event)
Function Documentation
afterFind ($ event) [inherited]
Apply any formats
Parameters:
CEvent $event
Returns:
mixed Apply any formats
Parameters:
CEvent $event
Definition at line 259 of file CXLDataTransformBehavior.php.
References CXLDataTransformBehavior.handleEvent().
afterValidate ($ event) [inherited]
Apply any formats
Parameters:
CEvent $event
Returns:
mixed
Definition at line 221 of file CXLDataTransformBehavior.php.
References CXLDataTransformBehavior.handleEvent().
beforeValidate ($ event) [inherited]
Apply formats before validation
Parameters:
CModelEvent $event parameter
Returns:
mixed
Definition at line 211 of file CXLDataTransformBehavior.php.
References CXLDataTransformBehavior.handleEvent().