<?php

require_once dirname( __FILE__ ) . '/../../../../lib/core/helpers/CXLHash.php';

/**
 * Test class for CXLHash.
 * Generated by PHPUnit on 2011-03-06 at 00:32:16.
 */
class CXLHashTest extends PHPUnit_Framework_TestCase
{

	/**
	 * @var CXLHash
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new CXLHash;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{

	}

	/**
	 * @todo Implement testGenerate().
	 */
	public function testGenerate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testHash().
	 */
	public function testHash()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

}

?>
